/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song16.c                                              *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Downloads\en.stm32cubef4\STM32Cube_FW_F4_V1.21.0\Middlewares\ST\STemWin\Software\hanzi.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4F4D[ 32] = { /* code 4F4D */
  ____X___,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __XX____,________,
  __XX____,____X___,
  _X_X__X_,____X___,
  X__X__X_,____X___,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,___X____,
  ___X___X,__X_____,
  ___X____,__X_____,
  ___XXXXX,XXXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_4F53[ 32] = { /* code 4F53 */
  ____X___,_X______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXX__,
  __XX____,_X______,
  __XX____,XXX_____,
  _X_X____,XXX_____,
  X__X___X,_X_X____,
  ___X___X,_X_X____,
  ___X__X_,_X__X___,
  ___X_X_X,XXXX_X__,
  ___XX___,_X____X_,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_516C[ 32] = { /* code 516C */
  ________,X_______,
  _____X__,X_______,
  _____X__,X_______,
  ____X___,_X______,
  ____X___,_X______,
  ___X____,__X_____,
  __X_____,___X____,
  _X____X_,____X___,
  X_____X_,_____XX_,
  _____X__,________,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,__X_____,
  __XXXXXX,XXXX____,
  ___X____,___X____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5316[ 32] = { /* code 5316 */
  ____X___,X_______,
  ____X___,X_______,
  ____X___,X____X__,
  ___X____,X___X___,
  ___X____,X__X____,
  __XX____,X_X_____,
  __XX____,XX______,
  _X_X____,X_______,
  X__X___X,X_______,
  ___X__X_,X_______,
  ___X_X__,X_______,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,_XXXXXX_,
  ___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_538B[ 32] = { /* code 538B */
  ________,________,
  __XXXXXX,XXXXXXX_,
  __X_____,________,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X_______,
  __X_XXXX,XXXXXX__,
  __X_____,X_______,
  __X_____,X_______,
  __X_____,X__X____,
  __X_____,X___X___,
  __X_____,X___X___,
  _X______,X_______,
  _X_XXXXX,XXXXXXX_,
  X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_539F[ 32] = { /* code 539F */
  ________,________,
  __XXXXXX,XXXXXXX_,
  __X_____,X_______,
  __X____X,________,
  __X__XXX,XXXX____,
  __X__X__,___X____,
  __X__X__,___X____,
  __X__XXX,XXXX____,
  __X__X__,___X____,
  __X__X__,___X____,
  __X__XXX,XXXX____,
  __X_____,X_______,
  __X__X__,X__X____,
  _X__X___,X___X___,
  _X_X__X_,X____X__,
  X______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_53F8[ 32] = { /* code 53F8 */
  ________,________,
  __XXXXXX,XXXXX___,
  ________,____X___,
  ________,____X___,
  _XXXXXXX,XXX_X___,
  ________,____X___,
  ________,____X___,
  ___XXXXX,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___X____,X___X___,
  ___XXXXX,X___X___,
  ___X____,X___X___,
  ________,__X_X___,
  ________,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_56FA[ 32] = { /* code 56FA */
  ________,________,
  _XXXXXXX,XXXXXX__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_XXXXX,XXXX_X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X__XXXX,XXX__X__,
  _X__X___,__X__X__,
  _X__X___,__X__X__,
  _X__X___,__X__X__,
  _X__XXXX,XXX__X__,
  _X__X___,__X__X__,
  _X______,_____X__,
  _XXXXXXX,XXXXXX__,
  _X______,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5927[ 32] = { /* code 5927 */
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  ______X_,X_______,
  ______X_,X_______,
  _____X__,_X______,
  _____X__,_X______,
  ____X___,__X_____,
  ___X____,___X____,
  __X_____,____X___,
  XX______,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5BFC[ 32] = { /* code 5BFC */
  ________,________,
  __XXXXXX,XXXX____,
  __X_____,___X____,
  __X_____,___X____,
  __XXXXXX,XXXX____,
  __X_____,_____X__,
  __X_____,_____X__,
  ___XXXXX,XXXXXX__,
  ________,__X_____,
  ________,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X___,__X_____,
  _____X__,__X_____,
  _____X__,__X_____,
  ________,X_X_____,
  ________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_5EA6[ 32] = { /* code 5EA6 */
  _______X,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __XXXXXX,XXXXXX__,
  __X___X_,__X_____,
  __X___X_,__X_____,
  __X___XX,XXX_____,
  __X_____,________,
  __X_XXXX,XXXX____,
  __X__X__,___X____,
  _X____X_,__X_____,
  _X_____X,XX______,
  X____XX_,__XX____,
  __XXX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6001[ 32] = { /* code 6001 */
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  ______X_,X_______,
  _____X__,_X______,
  ____X_X_,__X_____,
  __XX___X,___XX___,
  XX______,_____XX_,
  _______X,________,
  ____X___,X___X___,
  _X__X___,X____X__,
  _X__X___,___X__X_,
  _X__X___,___X__X_,
  X____XXX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_603B[ 32] = { /* code 603B */
  ___X____,___X____,
  ____X___,__X_____,
  _____X__,_X______,
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  _______X,________,
  ____X___,X____X__,
  _X__X___,X__X__X_,
  _X__X___,___X__X_,
  X____XXX,XXXX____,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6280[ 32] = { /* code 6280 */
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  XXXXXX__,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X_X_X,XXXXXX__,
  ___XX___,X____X__,
  __XX____,X___X___,
  XX_X____,_X__X___,
  ___X____,_X_X____,
  ___X____,__X_____,
  ___X____,_X_X____,
  _X_X___X,X___X___,
  __X__XX_,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6377[ 32] = { /* code 6377 */
  __X_____,_X______,
  __X_____,_X______,
  __X__XXX,XXXXXXX_,
  __X_____,_X______,
  XXXXX_XX,XXXXX___,
  __X_____,_X__X___,
  __X__XXX,XXXXXXX_,
  __X_X___,_X__X___,
  __XX__XX,XXXXX___,
  XXX_____,_X______,
  __X___X_,_X______,
  __X___X_,_XXXXX__,
  __X___X_,_X______,
  __X__X_X,_X______,
  X_X__X__,XXXXXXX_,
  _X__X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6613[ 32] = { /* code 6613 */
  ____XXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ____XXXX,XXXX____,
  _____X__,________,
  ____X___,________,
  ___XXXXX,XXXXXX__,
  __X___X_,_X___X__,
  _X____X_,_X___X__,
  _____X__,X____X__,
  ____X___,X____X__,
  ___X___X,__X_X___,
  ______X_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6709[ 32] = { /* code 6709 */
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,________,
  _____X__,________,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ___XX___,___X____,
  __X_XXXX,XXXX____,
  _X__X___,___X____,
  X___X___,___X____,
  ____XXXX,XXXX____,
  ____X___,___X____,
  ____X___,___X____,
  ____X___,_X_X____,
  ____X___,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6C14[ 32] = { /* code 6C14 */
  ___X____,________,
  ___X____,________,
  __XXXXXX,XXXXXX__,
  __X_____,________,
  _X__XXXX,XXXX____,
  X_______,________,
  __XXXXXX,XXXX____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,___X____,
  ________,____X_X_,
  ________,____X_X_,
  ________,_____XX_,
  ________,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6C27[ 32] = { /* code 6C27 */
  __X_____,________,
  __XXXXXX,XXXXXX__,
  _X______,________,
  X__XXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXXX____,
  ___X___X,___X____,
  ____X_X_,___X____,
  _XXXXXXX,XX_X____,
  _____X__,___X____,
  __XXXXXX,X__X____,
  _____X__,___X__X_,
  XXXXXXXX,XXX_X_X_,
  _____X__,____X_X_,
  _____X__,_____XX_,
  _____X__,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6C28[ 32] = { /* code 6C28 */
  __X_____,________,
  __XXXXXX,XXXXXX__,
  _X______,________,
  X__XXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXXX____,
  _____X__,___X____,
  _XXXXXXX,XX_X____,
  _X______,_X_X____,
  ____X___,___X____,
  XXXXXXXX,XX_X____,
  ___X___X,___X__X_,
  __XX__X_,____X_X_,
  ____XX__,____X_X_,
  ___XX_XX,_____XX_,
  _XX_____,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6C2E[ 32] = { /* code 6C2E */
  __X_____,________,
  __XXXXXX,XXXXXX__,
  _X______,________,
  X__XXXXX,XXXX____,
  ________,________,
  _XXXXXXX,XXXX____,
  _____X__,___X____,
  __X__X__,X__X____,
  ____X_XX,___X____,
  ___X____,X__X____,
  _XX_____,_X_X____,
  _____X__,___X__X_,
  __X__X__,X___X_X_,
  ____X_XX,____X_X_,
  ___X____,X____XX_,
  _XX_____,_X____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6E29[ 32] = { /* code 6E29 */
  ________,________,
  __X___XX,XXXXX___,
  ___X__X_,____X___,
  ___X__X_,____X___,
  X_____XX,XXXXX___,
  _X____X_,____X___,
  _X____X_,____X___,
  ___X__XX,XXXXX___,
  ___X____,________,
  __X__XXX,XXXXXX__,
  XXX__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X__X__,X_X__X__,
  __X_XXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_6EB6[ 32] = { /* code 6EB6 */
  ________,_X______,
  __X_____,__X_____,
  ___X__XX,XXXXXXX_,
  ___X__X_,______X_,
  X____X__,X__X_X__,
  _X_____X,____X___,
  _X__X_X_,_XX__X__,
  ____X___,X__X____,
  ___X___X,____X___,
  ___X__X_,_____X__,
  XXX__X_X,XXXXX_X_,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,XXXXX___,
  _______X,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7387[ 32] = { /* code 7387 */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  ______X_,________,
  _X___X__,_X___X__,
  __X_XXXX,X___X___,
  ___X___X,___X____,
  __X___X_,_X__X___,
  _X__XXXX,XXX__X__,
  ________,__X_____,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_751F[ 32] = { /* code 751F */
  _______X,________,
  ___X___X,________,
  ___X___X,________,
  ___X___X,________,
  __XXXXXX,XXXXXX__,
  __X____X,________,
  _X_____X,________,
  X______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_76D0[ 32] = { /* code 76D0 */
  ____X___,__X_____,
  ____X___,__X_____,
  _XXXXXXX,__X_____,
  ____X___,__X_X___,
  ____X___,__X__X__,
  ____XXXX,__X___X_,
  XXXX____,__X_____,
  _X______,__X_____,
  ________,________,
  __XXXXXX,XXXXX___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  __X__X__,_X__X___,
  XXXXXXXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_785D[ 32] = { /* code 785D */
  ________,__X_____,
  _______X,__X__X__,
  XXXXXX__,X_X__X__,
  ___X____,X_X_X___,
  ___X____,__X_____,
  __X____X,XXXXXX__,
  __XXXX_X,_____X__,
  _XX__X_X,_____X__,
  _XX__X_X,XXXXXX__,
  X_X__X_X,_____X__,
  __X__X_X,_____X__,
  __X__X_X,XXXXXX__,
  __XXXX_X,_____X__,
  __X__X_X,_____X__,
  __X____X,___X_X__,
  _______X,____X___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_78B1[ 32] = { /* code 78B1 */
  ________,___X_X__,
  ________,___X__X_,
  XXXX____,___X____,
  __X__XXX,XXXXXXX_,
  __X__X__,___X____,
  _X___X__,___X____,
  _XXX_X_X,XX_X____,
  XX_X_X__,___X__X_,
  _X_X_X__,___X__X_,
  _X_X_X_X,XX_X_X__,
  _X_X_X_X,_X_X_X__,
  _X_X_X_X,_X__X___,
  _XXX_X_X,XX_XX_X_,
  _X_X_X__,__X_X_X_,
  ____X___,_X___XX_,
  ___X____,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_795E[ 32] = { /* code 795E */
  __X_____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____,
  XXXXX__X,XXXXXX__,
  ____X__X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,__X__X__,
  __XXX__X,XXXXXX__,
  _X_X_X_X,__X__X__,
  X__X_X_X,__X__X__,
  ___X___X,__X__X__,
  ___X___X,XXXXXX__,
  ___X___X,__X__X__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_79D1[ 32] = { /* code 79D1 */
  ____X___,___X____,
  ___XXX_X,___X____,
  XXXX____,X__X____,
  ___X____,X__X____,
  ___X____,___X____,
  XXXXXX_X,___X____,
  ___X____,X__X____,
  __XXX___,X__X____,
  __XX_X__,___X____,
  _X_X____,___XXXX_,
  _X_X__XX,XXXX____,
  X__X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____,
  ___X____,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_89E3[ 32] = { /* code 89E3 */
  ___X____,________,
  ___X____,XXXXXX__,
  __XXXX__,__X__X__,
  __X__X__,__X__X__,
  _X__X___,_X_X_X__,
  X_XXXXX_,X___X___,
  __X_X_X_,___X____,
  __X_X_X_,_X_X____,
  __XXXXX_,_XXXXX__,
  __X_X_X_,X__X____,
  __X_X_X_,___X____,
  __XXXXX_,XXXXXXX_,
  __X_X_X_,___X____,
  _X__X_X_,___X____,
  _X____X_,___X____,
  X____XX_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_8FD8[ 32] = { /* code 8FD8 */
  ________,________,
  __X___XX,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ________,_X______,
  ________,_X______,
  XXXX____,XX_X____,
  ___X___X,_X__X___,
  ___X__X_,_X___X__,
  ___X_X__,_X___X__,
  ___X____,_X______,
  ___X____,_X______,
  ___X____,_X______,
  __X_X___,________,
  _X___XXX,XXXXXXX_,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9178[ 32] = { /* code 9178 */
  ________,___X____,
  XXXXXXX_,___X____,
  __X_X___,__X_____,
  __X_X___,_X___X__,
  XXXXXXX_,XXXXXXX_,
  X_X_X_X_,__X_X___,
  X_X_X_X_,_X___X__,
  X_X_X_X_,X_X___X_,
  X_X_XXX_,__XXXX__,
  XX____X_,_X___X__,
  X_____X_,_X___X__,
  XXXXXXX_,X_X_X___,
  X_____X_,___X____,
  X_____X_,__X_X___,
  XXXXXXX_,_X___X__,
  X_____X_,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_94F5[ 32] = { /* code 94F5 */
  __X_____,_X______,
  __X_____,__X_____,
  __XXX___,__X_____,
  __X___XX,XXXXXXX_,
  _X____X_,______X_,
  _XXXXX__,_X___X__,
  X_X_____,_X______,
  __X___XX,XXXXXXX_,
  XXXXX___,X___X___,
  __X_____,X___X___,
  __X____X,____X___,
  __X_____,XX_X____,
  __X_X___,__X_____,
  __XX____,_X_X____,
  __X_____,X___X___,
  ______XX,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong16_9650[ 32] = { /* code 9650 */
  ________,________,
  _XXXX_XX,XXXXX___,
  _X__X_X_,____X___,
  _X_X__X_,____X___,
  _X_X__XX,XXXXX___,
  _XX___X_,____X___,
  _X_X__X_,____X___,
  _X__X_XX,XXXXX___,
  _X__X_X_,_X___X__,
  _X__X_X_,_X__X___,
  _XX_X_X_,__XX____,
  _X_X__X_,__X_____,
  _X____X_,___X____,
  _X____X_,X___X___,
  _X____XX,_____XX_,
  _X____X_,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong16_CharInfo[36] = {
   {  16,  16,  2, acGUI_Fontsong16_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_Fontsong16_4F53 } /* code 4F53 */
  ,{  16,  16,  2, acGUI_Fontsong16_516C } /* code 516C */
  ,{  16,  16,  2, acGUI_Fontsong16_5316 } /* code 5316 */
  ,{  16,  16,  2, acGUI_Fontsong16_538B } /* code 538B */
  ,{  16,  16,  2, acGUI_Fontsong16_539F } /* code 539F */
  ,{  16,  16,  2, acGUI_Fontsong16_53F8 } /* code 53F8 */
  ,{  16,  16,  2, acGUI_Fontsong16_56FA } /* code 56FA */
  ,{  16,  16,  2, acGUI_Fontsong16_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_Fontsong16_5BFC } /* code 5BFC */
  ,{  16,  16,  2, acGUI_Fontsong16_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_Fontsong16_6001 } /* code 6001 */
  ,{  16,  16,  2, acGUI_Fontsong16_603B } /* code 603B */
  ,{  16,  16,  2, acGUI_Fontsong16_6280 } /* code 6280 */
  ,{  16,  16,  2, acGUI_Fontsong16_6377 } /* code 6377 */
  ,{  16,  16,  2, acGUI_Fontsong16_6613 } /* code 6613 */
  ,{  16,  16,  2, acGUI_Fontsong16_6709 } /* code 6709 */
  ,{  16,  16,  2, acGUI_Fontsong16_6C14 } /* code 6C14 */
  ,{  16,  16,  2, acGUI_Fontsong16_6C27 } /* code 6C27 */
  ,{  16,  16,  2, acGUI_Fontsong16_6C28 } /* code 6C28 */
  ,{  16,  16,  2, acGUI_Fontsong16_6C2E } /* code 6C2E */
  ,{  16,  16,  2, acGUI_Fontsong16_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_Fontsong16_6EB6 } /* code 6EB6 */
  ,{  16,  16,  2, acGUI_Fontsong16_7387 } /* code 7387 */
  ,{  16,  16,  2, acGUI_Fontsong16_751F } /* code 751F */
  ,{  16,  16,  2, acGUI_Fontsong16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fontsong16_76D0 } /* code 76D0 */
  ,{  16,  16,  2, acGUI_Fontsong16_785D } /* code 785D */
  ,{  16,  16,  2, acGUI_Fontsong16_78B1 } /* code 78B1 */
  ,{  16,  16,  2, acGUI_Fontsong16_795E } /* code 795E */
  ,{  16,  16,  2, acGUI_Fontsong16_79D1 } /* code 79D1 */
  ,{  16,  16,  2, acGUI_Fontsong16_89E3 } /* code 89E3 */
  ,{  16,  16,  2, acGUI_Fontsong16_8FD8 } /* code 8FD8 */
  ,{  16,  16,  2, acGUI_Fontsong16_9178 } /* code 9178 */
  ,{  16,  16,  2, acGUI_Fontsong16_94F5 } /* code 94F5 */
  ,{  16,  16,  2, acGUI_Fontsong16_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop35 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 35] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop34 = {
   0x94F5 /* first character */
  ,0x94F5 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontsong16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop33 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontsong16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop32 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontsong16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop31 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontsong16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop30 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontsong16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop29 = {
   0x795E /* first character */
  ,0x795E /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontsong16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop28 = {
   0x78B1 /* first character */
  ,0x78B1 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontsong16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop27 = {
   0x785D /* first character */
  ,0x785D /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontsong16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop26 = {
   0x76D0 /* first character */
  ,0x76D0 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontsong16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontsong16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop24 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontsong16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop23 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontsong16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop22 = {
   0x6EB6 /* first character */
  ,0x6EB6 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontsong16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop21 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontsong16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop20 = {
   0x6C2E /* first character */
  ,0x6C2E /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontsong16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop19 = {
   0x6C27 /* first character */
  ,0x6C28 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontsong16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop18 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontsong16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop17 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontsong16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop16 = {
   0x6613 /* first character */
  ,0x6613 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontsong16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop15 = {
   0x6377 /* first character */
  ,0x6377 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontsong16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop14 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsong16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop13 = {
   0x603B /* first character */
  ,0x603B /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsong16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop12 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontsong16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop11 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontsong16_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontsong16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop10 = {
   0x5BFC /* first character */
  ,0x5BFC /* last character  */
  ,&GUI_Fontsong16_CharInfo[  9] /* address of first character */
  ,&GUI_Fontsong16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop9 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  8] /* address of first character */
  ,&GUI_Fontsong16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop8 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_Fontsong16_CharInfo[  7] /* address of first character */
  ,&GUI_Fontsong16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop7 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  6] /* address of first character */
  ,&GUI_Fontsong16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop6 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_Fontsong16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontsong16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop5 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontsong16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontsong16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop4 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontsong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontsong16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontsong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontsong16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong16_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontsong16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

