/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: youyuan24.c                                           *
* Font:        свт╡                                                  *
* Height:      24                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  24                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Downloads\en.stm32cubef4\STM32Cube_FW_F4_V1.21.0\Middlewares\ST\STemWin\Software\hanzi.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan24;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_4F4D[ 72] = { /* code 4F4D */
  ________,________,________,
  ________,________,________,
  _____X__,_____X__,________,
  _____X__,_____XX_,________,
  _____X__,______X_,________,
  _____X__,______X_,________,
  ____XX_X,XXXXXXXX,XXXXXXX_,
  ____X___,________,________,
  ___XX___,________,___X____,
  ___XX___,_X______,___X____,
  __XXX___,_X______,___X____,
  __X_X___,_XX_____,___X____,
  _XX_X___,__X_____,___X____,
  XX__X___,__X_____,__XX____,
  ____X___,__X_____,__X_____,
  ____X___,__X_____,__X_____,
  ____X___,__XX____,__X_____,
  ____X___,___X____,_XX_____,
  ____X___,___X____,_X______,
  ____X___,___X____,_X______,
  ____X___,___X____,XX______,
  ____X___,___X____,X_______,
  ____X_XX,XXXXXXXX,XXXXXXX_,
  ____X_XX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_4F53[ 72] = { /* code 4F53 */
  ________,________,________,
  ________,________,________,
  _____X__,_____XX_,________,
  _____X__,_____XX_,________,
  _____X__,_____XX_,________,
  _____X__,_____XX_,________,
  ____XX__,_____XX_,________,
  ____X__X,XXXXXXXX,XXXXXXX_,
  ____X___,_____XX_,________,
  ___XX___,_____XXX,________,
  ___XX___,____XXXX,________,
  __X_X___,____XXXX,X_______,
  _XX_X___,___X_XX_,X_______,
  _X__X___,__XX_XX_,_X______,
  ____X___,__X__XX_,_XX_____,
  ____X___,_X___XX_,__XX____,
  ____X___,XX___XX_,___X____,
  ____X__X,X____XX_,____X___,
  ____X_XX,_XXXXXXX,XXX__X__,
  ____XXX_,_XXXXXXX,XXX___X_,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________,
  ____X___,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_516C[ 72] = { /* code 516C */
  ________,________,________,
  ________,________,________,
  ________,______X_,________,
  ________,X_____XX,________,
  ________,X______X,________,
  _______X,_______X,X_______,
  ______XX,________,X_______,
  ______X_,________,XX______,
  _____XX_,________,_XX_____,
  ____XX__,________,__X_____,
  ___XX___,___X____,___X____,
  ___X____,__X_____,____X___,
  _XX_____,__X_____,_____X__,
  _X______,_X______,______X_,
  ________,_X______,X_______,
  ________,X_______,XX______,
  _______X,X_______,_X______,
  _______X,________,_XX_____,
  ______X_,________,__X_____,
  _____XX_,________,___X____,
  _____X__,________,___X____,
  ____XX__,__XXXXXX,XXXXX___,
  ____XXXX,XXX_____,____X___,
  ________,________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_5316[ 72] = { /* code 5316 */
  ________,________,________,
  ________,________,________,
  ______X_,_____X__,________,
  ______X_,_____X__,________,
  ______X_,_____X__,________,
  _____XX_,_____X__,____X___,
  _____X__,_____X__,____X___,
  _____X__,_____X__,___X____,
  ____XX__,_____X__,__X_____,
  ____X___,_____X__,XX______,
  ___XX___,_____X_X,X_______,
  __XXX___,_____XXX,________,
  __X_X___,____XX__,________,
  _X__X___,__XX_X__,________,
  ____X__X,XX___X__,________,
  ____X__X,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,______X_,
  ____X___,_____X__,______X_,
  ____X___,_____X__,______X_,
  ____X___,_____X__,_____XX_,
  ____X___,_____X__,_____X__,
  ____X___,_____X__,_____X__,
  ____X___,_____XXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_538B[ 72] = { /* code 538B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XX____,________,________,
  __XX____,____X___,________,
  __XX____,____X___,________,
  __XX____,____X___,________,
  __XX____,____X___,________,
  __XX____,____X___,________,
  __XX__XX,XXXXXXXX,XXXXX___,
  __XX__XX,XXXXXXXX,XXXXX___,
  __XX____,____X___,________,
  __XX____,____X___,X_______,
  __XX____,____X___,XX______,
  __XX____,____X___,_X______,
  __XX____,____X___,_XX_____,
  __X_____,____X___,__X_____,
  __X_____,____X___,__XX____,
  __X_____,____X___,________,
  __X_____,____X___,________,
  __X_XXXX,XXXXXXXX,XXXXXXX_,
  _X______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_539F[ 72] = { /* code 539F */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __X_____,____XX__,________,
  __X_____,____X___,________,
  __X____X,XXXXXXXX,XXXX____,
  __X___XX,XXXXXXXX,XXXXX___,
  __X___X_,________,____X___,
  __X___X_,________,____X___,
  __X___XX,XXXXXXXX,XXXXX___,
  __X___X_,________,____X___,
  __X___X_,________,____X___,
  __X___X_,________,____X___,
  __X___X_,________,____X___,
  __X___XX,XXXXXXXX,XXXXX___,
  __X_____,_____X__,________,
  __X_____,X____X__,_XX_____,
  __X_____,X____X__,__X_____,
  __X____X,_____X__,___X____,
  __X___XX,_____X__,___XX___,
  _XX__XX_,_____X__,____X___,
  _X__XX__,_____X__,_____X__,
  _X__X___,_XXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_53F8[ 72] = { /* code 53F8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,________,____XX__,
  ________,________,____XX__,
  ________,________,____XX__,
  _XXXXXXX,XXXXXXXX,XXX_XX__,
  ________,________,____XX__,
  ________,________,____XX__,
  ________,________,____XX__,
  ___XXXXX,XXXXXXXX,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___X____,________,X___XX__,
  ___XXXXX,XXXXXXXX,X___XX__,
  ________,________,____XX__,
  ________,________,____XX__,
  ________,_____XXX,____XX__,
  ________,_______X,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_56FA[ 72] = { /* code 56FA */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XX____,________,_____X__,
  __X_____,___XX___,_____X__,
  __X_____,___XX___,_____X__,
  __X_____,___XX___,_____X__,
  __X_XXXX,XXXXXXXX,XXXX_X__,
  __X_____,___XX___,_____X__,
  __X_____,___XX___,_____X__,
  __X_____,___XX___,_____X__,
  __X____X,XXXXXXXX,X____X__,
  __X___XX,________,_X___X__,
  __X___X_,________,_X___X__,
  __X___X_,________,_X___X__,
  __X___X_,________,_X___X__,
  __X___X_,________,_X___X__,
  __X___X_,________,_X___X__,
  __X___XX,XXXXXXXX,XX___X__,
  __X_____,________,_____X__,
  __X_____,________,_____X__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_5927[ 72] = { /* code 5927 */
  ________,________,________,
  ________,________,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,___X____,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XXXX__,________,
  ________,__X__X__,________,
  ________,__X__X__,________,
  ________,_XX___X_,________,
  ________,_X____X_,________,
  ________,X______X,________,
  _______X,X______X,X_______,
  _______X,________,XX______,
  _____XX_,________,_XX_____,
  ____XX__,________,__XX____,
  __XXX___,________,___XX___,
  _XX_____,________,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_5BFC[ 72] = { /* code 5BFC */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,________,__X_____,
  ____X___,________,__X_____,
  ____X___,________,__X_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ____X___,________,_____X__,
  ____X___,________,_____X__,
  ____X___,________,_____X__,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ________,________,_XX_____,
  ________,________,_XX_____,
  ________,________,_XX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,________,_XX_____,
  ______XX,________,_XX_____,
  _______X,X_______,_XX_____,
  ________,XX______,_XX_____,
  ________,_XX_____,_XX_____,
  ________,__X_____,_XX_____,
  ________,____XX__,_XX_____,
  ________,_____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_5EA6[ 72] = { /* code 5EA6 */
  ________,________,________,
  ________,________,________,
  ________,___X____,________,
  ________,___XX___,________,
  ___XXXXX,XXXXXXXX,XXXXXX__,
  ___X____,________,________,
  __XX____,X_______,XX______,
  __XX____,X_______,XX______,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XX____,X_______,XX______,
  __XX____,X_______,XX______,
  __XX____,X_______,XX______,
  __XX____,XXXXXXXX,X_______,
  __XX____,________,________,
  __XX____,________,________,
  __XX_XXX,XXXXXXXX,XXXX____,
  __XX___X,X_______,__XX____,
  __X_____,XX______,_XX_____,
  __X_____,_XX____X,XX______,
  __X_____,__XX__XX,________,
  __X_____,___XXX__,________,
  __X_____,_XXX_XX_,________,
  _X____XX,XX_____X,XX______,
  _X_XXXX_,________,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6001[ 72] = { /* code 6001 */
  ________,________,________,
  ________,________,________,
  ________,___XX___,________,
  ________,___X____,________,
  ________,___X____,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXX___,________,
  ________,__X__X__,________,
  ________,_X___XX_,________,
  ________,X______X,________,
  ______XX,___X____,XX______,
  ____XXX_,___XX___,_XXX____,
  _XXX____,____X___,____XXX_,
  ________,_____X__,________,
  ________,___X____,________,
  ____X__X,X__XX___,__X_____,
  ____X__X,X___X___,___X____,
  ___XX__X,X___XX__,___XX___,
  ___X___X,X____X__,_X__X___,
  ___X___X,X____XX_,_X__XX__,
  __XX___X,X_____X_,_X___X__,
  __X____X,X_______,_X___X__,
  _XX_____,X_______,_X____X_,
  _X______,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_603B[ 72] = { /* code 603B */
  ________,________,________,
  ________,________,________,
  ______X_,________,XX______,
  ______XX,________,X_______,
  _______X,________,X_______,
  _______X,X______X,________,
  ________,X_____XX,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ___X____,________,___X____,
  ___X____,________,___X____,
  ___X____,________,___X____,
  ___X____,________,___X____,
  ___X____,________,___X____,
  ___X____,________,___X____,
  ____XXXX,XXXXXXXX,XXXX____,
  ________,________,________,
  _______X,___X____,________,
  ___X___X,___X____,____X___,
  ___X___X,____X___,_X__X___,
  __XX___X,____X___,_X___X__,
  __X____X,____XX__,_X___X__,
  __X____X,_____X__,_X___XX_,
  _XX____X,________,_X____X_,
  _X_____X,XXXXXXXX,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6280[ 72] = { /* code 6280 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____X___,______XX,________,
  ____X___,______XX,________,
  ____X___,XXXXXXXX,XXXXXX__,
  ____X___,______XX,________,
  _XXXXXXX,______XX,________,
  _XXXXXXX,X_____XX,________,
  ____X___,______XX,________,
  ____X___,_XXXXXXX,XXXXX___,
  ____X___,__X_____,____X___,
  ____X___,__XX____,____X___,
  ____X__X,X__X____,___XX___,
  ____XXX_,___XX___,___X____,
  ___XXX__,____X___,__X_____,
  _XXXX___,____XX__,_XX_____,
  ____X___,_____XX_,XX______,
  ____X___,______XX,X_______,
  ____X___,______XX,X_______,
  ____X___,____XX__,XX______,
  ____X___,__XXX___,_XXX____,
  ____X___,XXX_____,___XX___,
  _XXXX_XX,________,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6377[ 72] = { /* code 6377 */
  ________,________,________,
  ________,________,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_______X,________,
  ____XX__,_XXXXXXX,XXXXXX__,
  ____XX__,_______X,________,
  _XXXXXXX,_______X,________,
  ____XX__,_XXXXXXX,XXXXX___,
  ____XX__,_______X,____X___,
  ____XX__,_______X,____X___,
  ____XX__,XXXXXXXX,XXXXXXX_,
  ____XX__,_______X,____X___,
  ____XX__,_______X,____X___,
  ____XX_X,XXXXXXXX,XXXXX___,
  ____XXXX,__X____X,________,
  _XXXXX__,__X____X,________,
  ____XX__,__X____X,XXXXXX__,
  ____XX__,__X____X,XXXXXX__,
  ____XX__,_XX____X,________,
  ____XX__,_X_X___X,________,
  ____XX__,XX__XX_X,________,
  ____XX__,X____XXX,________,
  _XXXX__X,________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6613[ 72] = { /* code 6613 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XXXX____,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ___XX___,________,___XX___,
  ____XXXX,XXXXXXXX,XXXX____,
  _______X,________,________,
  ______X_,________,________,
  _____XXX,XXXXXXXX,XXXXXX__,
  ___XX___,__XX____,X____X__,
  __XX____,_XX____X,X____X__,
  ________,XX____XX,_____X__,
  _______X,X_____X_,_____X__,
  _____XX_,____XX__,_____X__,
  __XXX___,___XX___,_____X__,
  _XX_____,__XX____,____XX__,
  ________,XX______,____X___,
  _____XXX,______XX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6709[ 72] = { /* code 6709 */
  ________,________,________,
  ________,________,________,
  ________,__X_____,________,
  ________,__X_____,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  _XXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,X_______,________,
  _______X,________,________,
  ______X_,________,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ___XXX__,________,____X___,
  _XXX_X__,________,___XX___,
  XX___X__,________,___XX___,
  _____XXX,XXXXXXXX,XXXXX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____XXX,XXXXXXXX,XXXXX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,_______X,___XX___,
  _____X__,_______X,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6C14[ 72] = { /* code 6C14 */
  ________,________,________,
  ________,________,________,
  ______X_,________,________,
  _____XX_,________,________,
  _____XXX,XXXXXXXX,XXXXXX__,
  ____XX__,________,________,
  ___XX___,________,________,
  __XX_XXX,XXXXXXXX,XXX_____,
  _X___XXX,XXXXXXXX,XXX_____,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,________,__XX____,
  ________,________,___X____,
  ________,________,___X____,
  ________,________,___X____,
  ________,________,___X____,
  ________,________,___X____,
  ________,________,___X__X_,
  ________,________,___X__X_,
  ________,________,___X__X_,
  ________,________,___XX_X_,
  ________,________,____X_X_,
  ________,________,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6C27[ 72] = { /* code 6C27 */
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____XXXX,XXXXXXXX,XXXXXX__,
  ____X___,________,________,
  ___XX___,________,________,
  ___X__XX,XXXXXXXX,XXXX____,
  __X_____,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  _____X__,______X_,___X____,
  _____X__,_____X__,___X____,
  ______X_,____XX__,___X____,
  __XXXXXX,XXXXXXXX,XX_X____,
  ________,_X______,___X____,
  ________,_X______,___X____,
  __XXXXXX,XXXXXXXX,X__X____,
  ________,_X______,___X__X_,
  ________,_X______,___X__X_,
  _XXXXXXX,XXXXXXXX,XX_X__X_,
  ________,_X______,____X_X_,
  ________,_X______,____X_X_,
  ________,_X______,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6C28[ 72] = { /* code 6C28 */
  ________,________,________,
  ________,________,________,
  ______X_,________,________,
  _____XX_,________,________,
  _____XXX,XXXXXXXX,XXXXXX__,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  __XX_XXX,XXXXXXXX,XXXX____,
  _XX_____,________,________,
  ___XXXXX,XXXXXXXX,XXX_____,
  ________,_X______,__XX____,
  ________,_X______,___X____,
  ___XXXXX,XXXXXXXX,X__X____,
  __XX____,________,XX_X____,
  __X_____,X_______,X__X____,
  __X____X,________,X__X____,
  __XXXXXX,XXXXXXXX,X__X____,
  ______X_,_____XX_,___X____,
  _____X__,_____X__,___X__X_,
  _____XXX,____XX__,___X__X_,
  _______X,XX_XX___,___X__X_,
  ________,__XXX___,___XX_X_,
  ______XX,XX__XXXX,____XXX_,
  _XXXXXX_,_______X,XX__XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6C2E[ 72] = { /* code 6C2E */
  ________,________,________,
  ________,________,________,
  ______X_,________,________,
  _____X__,________,________,
  _____XXX,XXXXXXXX,XXXXXX__,
  ____X___,________,________,
  ___XX___,________,________,
  __XX_XXX,XXXXXXXX,XXXX____,
  _XX_____,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  ________,_X______,___X____,
  ______X_,_X____XX,___X____,
  _____X__,_X____X_,___X____,
  _____X__,_X___X__,___X____,
  ________,XXXX____,___X____,
  ______XX,X___XX__,___X____,
  ___XXXX_,__X___XX,___X____,
  ______X_,__X__X__,X__X__X_,
  ______X_,_XX__X__,___X__X_,
  _____X__,_XX_X___,___X__X_,
  ________,XXXXX___,___XX_X_,
  _______X,X____XX_,____XXX_,
  __XXXXX_,_______X,X___XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6E29[ 72] = { /* code 6E29 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __X_____,XXXXXXXX,XXXX____,
  ___XX___,X_______,___XX___,
  ____XX_X,X_______,___XX___,
  _____X_X,X_______,___XX___,
  ______XX,XXXXXXXX,XXXXX___,
  _X_____X,X_______,___XX___,
  _XX____X,X_______,___XX___,
  __XX___X,X_______,____X___,
  ____X___,XXXXXXXX,XXXXX___,
  _____X__,________,________,
  ________,________,________,
  _____X__,________,________,
  ____XX_X,XXXXXXXX,XXXXX___,
  ____X__X,___X____,X___X___,
  ____X__X,___X____,X___X___,
  ____X__X,___X____,X___X___,
  ___X___X,___X____,X___X___,
  ___X___X,___X____,X___X___,
  __XX___X,___X____,X___X___,
  __X____X,___X____,X___X___,
  _X___XXX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_6EB6[ 72] = { /* code 6EB6 */
  ________,________,________,
  ________,________,________,
  ________,_____X__,________,
  ________,_____XX_,________,
  __XX___X,XXXXXXXX,XXXXXX__,
  ___XX_XX,________,_____XX_,
  ____XXXX,________,______X_,
  ______XX,___X____,XX___XX_,
  ______XX,_XX_____,_XX__X__,
  ________,XX___XX_,___XX___,
  _XX____X,X___XX_X,____X___,
  __XX____,___XX___,X_______,
  ____XX__,__XX____,_X______,
  ________,_XX_____,__XX____,
  ________,XX______,___XX___,
  _____X_X,X_______,____XX__,
  ____XXX_,XXXXXXXX,XXXXX_X_,
  ____X___,X_______,____X___,
  ____X___,X_______,____X___,
  ___X____,X_______,____X___,
  ___X____,X_______,____X___,
  __X_____,X_______,____X___,
  __X_____,XXXXXXXX,XXXXX___,
  _X______,_XXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_7387[ 72] = { /* code 7387 */
  ________,________,________,
  ________,________,________,
  ________,___X____,________,
  ________,___XX___,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,________,
  __X_____,__XX____,____X___,
  __XX____,__X_____,__XXX___,
  ____X___,_XX__X__,XXX_____,
  _____X__,_X__XX_X,X_______,
  _____X__,XXXXX___,________,
  _______X,XXXX___X,________,
  ______X_,__XX____,X_______,
  ____XX__,__X__X__,_X______,
  ___XX___,_X____X_,__X_____,
  __XX____,XXXXXXXX,___X____,
  ________,X__X___X,____X___,
  ________,___X____,________,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXX__,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_751F[ 72] = { /* code 751F */
  ________,________,________,
  ________,________,________,
  ________,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____XXXX,XXXXXXXX,XXXXX___,
  ____X___,____X___,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  __X_____,____X___,________,
  _XX_____,____X___,________,
  _X______,____X___,________,
  ________,____X___,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  ________,____X___,________,
  _XXXXXXX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_7535[ 72] = { /* code 7535 */
  ________,________,________,
  ________,________,________,
  ________,___X____,________,
  ________,___X____,________,
  ________,___X____,________,
  ___XXXXX,XXXXXXXX,XXXX____,
  __XX____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __XXXXXX,XXXXXXXX,XXXX____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __X_____,___X____,___X____,
  __XXXXXX,XXXXXXXX,XXXX____,
  ________,___X____,______X_,
  ________,___X____,______X_,
  ________,___X____,______X_,
  ________,___X____,______X_,
  ________,___XXXXX,XXXXXX__,
  ________,____XXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_76D0[ 72] = { /* code 76D0 */
  ________,________,________,
  ________,________,________,
  ______X_,______XX,________,
  ______X_,______XX,________,
  ______X_,______XX,________,
  __XXXXXX,XXX___XX,________,
  __XXXXXX,XXX___XX,_X______,
  ______X_,______XX,__X_____,
  ______X_,______XX,___X____,
  ______X_,______XX,____X___,
  ______X_,__X___XX,_____X__,
  ______XX,XX____XX,______X_,
  ____XXXX,______XX,________,
  _XXXX___,______XX,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XXXXX___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  __XX____,XX____XX,____X___,
  _XXXXXXX,XXXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_785D[ 72] = { /* code 785D */
  ________,________,________,
  ________,________,________,
  ________,________,X_______,
  ________,___X____,X____X__,
  _XXXXXXX,X__X____,X___XX__,
  ____X___,____X___,X___X___,
  ____X___,____X___,X__XX___,
  ____X___,____XX__,X__X____,
  ____X___,________,X_______,
  ___XX___,___XXXXX,XXXXXX__,
  ___XXXXX,___X____,_____X__,
  ___X___X,__XX____,_____X__,
  __XX___X,__XX____,_____X__,
  __XX___X,__XXXXXX,XXXXXX__,
  _X_X___X,__XX____,_____X__,
  _X_X___X,__XX____,_____X__,
  ___X___X,__XX____,_____X__,
  ___X___X,__XXXXXX,XXXXXX__,
  ___X___X,__XX____,_____X__,
  ___X___X,__XX____,_____X__,
  ___X___X,__XX____,_____X__,
  ___X___X,__XX____,_____X__,
  ___XXX_X,__XX____,_____X__,
  ____XXXX,__XX____,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_78B1[ 72] = { /* code 78B1 */
  ________,________,________,
  ________,________,________,
  ________,________,__X_X___,
  ________,________,__X_XX__,
  _XXXXXXX,X_XXXXXX,XXXXXX__,
  _____X__,_XX_____,__X__X__,
  ____XX__,_XX_____,__X___X_,
  ____X___,_XX_XXXX,X_X_____,
  ____X___,_XX_____,__X_____,
  ___X____,_XX_____,__X_____,
  ___XXXX_,_XX___X_,__X_XX__,
  __XX__XX,_XX_XXXX,X_X_XX__,
  __XX___X,_XX_X___,X_X_X___,
  _XXX___X,_XX_X___,X_X_X___,
  _X_X___X,_XX_X___,X_X_X___,
  X__X___X,_XX_X___,X_X_X___,
  ___X___X,_XX_X___,X_X_X___,
  ___X___X,_X__X___,X_XXX___,
  ___X___X,_X__X___,X_XX__X_,
  ___X___X,_X__X__X,X_XX__X_,
  ___X___X,_X__XXXX,_XXX__X_,
  ___X___X,XX______,_X_XX_X_,
  ___XXXX_,X_______,X___XXX_,
  ________,X_____XX,____XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_795E[ 72] = { /* code 795E */
  ________,________,________,
  ________,________,________,
  ____X___,________,X_______,
  ____XX__,________,X_______,
  _____XX_,________,X_______,
  ______X_,________,X_______,
  __XXXXXX,X_XXXXXX,XXXXXX__,
  ________,X_X_____,X____X__,
  ________,X_X_____,X____X__,
  _______X,__X_____,X____X__,
  ______XX,__X_____,X____X__,
  ______X_,__X_____,X____X__,
  _____XX_,__XXXXXX,XXXXXX__,
  ____XXXX,__X_____,X____X__,
  ___X_X_X,X_X_____,X____X__,
  __X__X__,XXX_____,X____X__,
  _X___X__,_XX_____,X____X__,
  _____X__,__XX____,X____X__,
  _____X__,___XXXXX,XXXXXX__,
  _____X__,________,X_______,
  _____X__,________,X_______,
  _____X__,________,X_______,
  _____X__,________,X_______,
  _____X__,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_79D1[ 72] = { /* code 79D1 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XX___X__,___XX___,
  _____X__,_____XX_,___XX___,
  _____X__,______XX,___XX___,
  _____X__,_______X,X__XX___,
  _____X__,________,X__XX___,
  _____X__,________,_X_XX___,
  _XXXXXXX,XX_X____,__XXX___,
  _____XX_,___XX___,___XX___,
  _____XXX,_____X__,___XX___,
  ____XX_X,X_____X_,___XX___,
  ____XX__,X______X,___XX___,
  ___XXX__,XX_____X,X__XX___,
  ___X_X__,_X______,X__XX___,
  __X__X__,________,___XX___,
  _XX__X__,________,XXXXXXX_,
  _X___X__,_XXXXXXX,X__XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___,
  _____X__,________,___XX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_89E3[ 72] = { /* code 89E3 */
  ________,________,________,
  ________,________,________,
  _____X__,________,________,
  _____XXX,XX__XXXX,XXXXXX__,
  ____X___,_XX____X,X____X__,
  ___XX___,_X_____X,_____X__,
  __XX____,X_____XX,_____X__,
  _XXXXXXX,XX____X_,_____X__,
  _XXX__X_,__X__X__,XXXXXX__,
  __X___X_,__X_X___,________,
  __X___X_,__X__XX_,_X______,
  __X___X_,__X__X__,_X______,
  __XXXXXX,XXX__X__,_X______,
  __X___X_,__X__XXX,XXXXXXX_,
  __X___X_,__X_X___,_X______,
  __X___X_,__X_X___,_X______,
  __X___X_,__X_X___,_X______,
  __XXXXXX,XXX_XXXX,XXXXXXX_,
  __X___X_,__X_XXXX,XXXXXXX_,
  __X___X_,__X_____,_X______,
  __X___X_,__X_____,_X______,
  __X___X_,__X_____,_X______,
  _XX____X,__X_____,_X______,
  _X_____X,XXX_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_8FD8[ 72] = { /* code 8FD8 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___X____,________,________,
  ___XX___,XXXXXXXX,XXXXXX__,
  ____X___,_______X,X_______,
  ____XX__,_______X,________,
  ________,_______X,________,
  ________,______XX,________,
  ________,______X_,_X______,
  _XXXXX__,_____XX_,_X______,
  _____X__,____XXX_,__X_____,
  _____X__,____X_X_,__XX____,
  _____X__,___X__X_,___X____,
  _____X__,__XX__X_,___XX___,
  _____X__,_XX___X_,____X___,
  _____X__,XX____X_,_____X__,
  _____X_X,X_____X_,_____X__,
  _____X_X,______X_,______X_,
  ____XXX_,______X_,________,
  ____X_XX,______X_,________,
  ___X___X,X_____X_,________,
  __X_____,XXX_____,________,
  ________,__XXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_9178[ 72] = { /* code 9178 */
  ________,________,________,
  ________,________,________,
  ________,_______X,________,
  _XXXXXXX,XXX____X,___X____,
  ____X__X,______X_,___X____,
  ____X__X,_____XX_,____X___,
  ____X__X,_____X__,____XX__,
  __XXXXXX,XX__XXXX,XXXXXX__,
  __X_X__X,_XX_XXX_,______X_,
  _XX_X__X,_XX__XX_,__XX____,
  _XX_X__X,_XX__X__,___XX___,
  _XX_X__X,_XX_X___,____XX__,
  _XX_X__X,_XXX__X_,_____XX_,
  _XX_X__X,_XX___XX,XXXX____,
  _XX_X__X,_XX__XXX,XXXXX___,
  _XXXX___,XXX__XX_,____X___,
  _XXX____,_XX_XXX_,___XX___,
  _XX_____,_XXXX_XX,___X____,
  _XX_____,_XXX___X,__XX____,
  _XXXXXXX,XXX____X,XXX_____,
  _XX_____,_XX_____,XX______,
  _XX_____,_XX____X,XXX_____,
  __X_XXXX,_X___XX_,__XXX___,
  __XXXXXX,XX_XX___,____XXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_94F5[ 72] = { /* code 94F5 */
  ________,________,________,
  ________,________,________,
  ___X____,______X_,________,
  ___X____,_______X,________,
  ___XXXXX,__XXXXXX,XXXXXX__,
  ___XXXXX,XXX_____,_____X__,
  __X_____,_X_____X,_____X__,
  __X_____,_X_____X,_____X__,
  _X______,_X____X_,_____X__,
  ________,_X____X_,________,
  _XXXXXXX,_____XX_,________,
  ____X___,_XXXXXXX,XXXXXXX_,
  ____X___,_____X__,___X____,
  ____X___,____X___,___X____,
  _XXXXXXX,X___X___,__XX____,
  ____X___,___X____,__X_____,
  ____X___,___XX___,__X_____,
  ____X___,_____XX_,_X______,
  ____X___,______XX,_X______,
  ____X___,X_______,XX______,
  ____X__X,X_____XX,_XX_____,
  ____X_XX,_____XX_,___X____,
  ____XX__,___XX___,____XX__,
  ________,_XX_____,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan24_9650[ 72] = { /* code 9650 */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXXX_,__XXXXXX,XXXXX___,
  __X____X,__X_____,____X___,
  __X___XX,__X_____,____X___,
  __X___X_,__X_____,____X___,
  __X___X_,__X_____,____X___,
  __X___X_,__XXXXXX,XXXXX___,
  __X__X__,__X_____,____X___,
  __X__X__,__X_____,____X___,
  __X___X_,__X_____,____X___,
  __X___X_,__X_____,___XX___,
  __X____X,__XXXXXX,XXXX____,
  __X____X,__X___X_,________,
  __X____X,__X___X_,____XX__,
  __X____X,__X___X_,___XX___,
  __XXXXXX,__X____X,__XX____,
  __X_____,__X____X,XX______,
  __X_____,__X_____,XX______,
  __X_____,__X_____,_XX_____,
  __X_____,__X_____,__XX____,
  __X_____,__X__XXX,___XX___,
  __X_____,__XXXX__,_____XX_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan24_CharInfo[36] = {
   {  24,  24,  3, acGUI_Fontyouyuan24_4F4D } /* code 4F4D */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_4F53 } /* code 4F53 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_516C } /* code 516C */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_5316 } /* code 5316 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_538B } /* code 538B */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_539F } /* code 539F */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_53F8 } /* code 53F8 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_56FA } /* code 56FA */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_5927 } /* code 5927 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_5BFC } /* code 5BFC */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_5EA6 } /* code 5EA6 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6001 } /* code 6001 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_603B } /* code 603B */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6280 } /* code 6280 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6377 } /* code 6377 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6613 } /* code 6613 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6709 } /* code 6709 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6C14 } /* code 6C14 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6C27 } /* code 6C27 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6C28 } /* code 6C28 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6C2E } /* code 6C2E */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6E29 } /* code 6E29 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_6EB6 } /* code 6EB6 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_7387 } /* code 7387 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_751F } /* code 751F */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_7535 } /* code 7535 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_76D0 } /* code 76D0 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_785D } /* code 785D */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_78B1 } /* code 78B1 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_795E } /* code 795E */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_79D1 } /* code 79D1 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_89E3 } /* code 89E3 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_8FD8 } /* code 8FD8 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_9178 } /* code 9178 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_94F5 } /* code 94F5 */
  ,{  24,  24,  3, acGUI_Fontyouyuan24_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop35 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 35] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop34 = {
   0x94F5 /* first character */
  ,0x94F5 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop33 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop32 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop31 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop30 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop29 = {
   0x795E /* first character */
  ,0x795E /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop28 = {
   0x78B1 /* first character */
  ,0x78B1 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop27 = {
   0x785D /* first character */
  ,0x785D /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop26 = {
   0x76D0 /* first character */
  ,0x76D0 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop24 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop23 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop22 = {
   0x6EB6 /* first character */
  ,0x6EB6 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop21 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop20 = {
   0x6C2E /* first character */
  ,0x6C2E /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop19 = {
   0x6C27 /* first character */
  ,0x6C28 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop18 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop17 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop16 = {
   0x6613 /* first character */
  ,0x6613 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop15 = {
   0x6377 /* first character */
  ,0x6377 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop14 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop13 = {
   0x603B /* first character */
  ,0x603B /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop12 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop11 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop10 = {
   0x5BFC /* first character */
  ,0x5BFC /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  9] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop9 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  8] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop8 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  7] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop7 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop6 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop5 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop4 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan24_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontyouyuan24_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan24_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan24 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,24 /* height of font  */
  ,24 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan24_Prop1}
  ,21 /* Baseline */
  ,11 /* Height of lowercase characters */
  ,16 /* Height of capital characters */
};

