/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: youyuan16.c                                           *
* Font:        свт╡                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Downloads\en.stm32cubef4\STM32Cube_FW_F4_V1.21.0\Middlewares\ST\STemWin\Software\hanzi.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_4F4D[ 32] = { /* code 4F4D */
  ________,________,
  ________,________,
  ___X____,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  __X_____,____X___,
  __X___X_,_____X__,
  _XX___X_,____X___,
  _XX___X_,____X___,
  __X___X_,____X___,
  __X____X,____X___,
  __X____X,___X____,
  __X____X,___X____,
  __X____X,___X____,
  __X_____,___X____,
  __X_XXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_4F53[ 32] = { /* code 4F53 */
  ________,________,
  ________,_X______,
  ___X____,_X______,
  ___X____,_X______,
  ___X_XXX,XXXXXXX_,
  __X_X___,_X______,
  __X_____,XXX_____,
  _XX_____,XXX_____,
  _XX____X,_X_X____,
  X_X____X,_X_X____,
  __X___X_,_X__X___,
  __X__X__,_X___X__,
  __X_X_XX,XXXXX_X_,
  __XX____,_X______,
  __X_____,_X______,
  __X_____,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_516C[ 32] = { /* code 516C */
  ________,________,
  ________,________,
  _____X__,_X______,
  _____X__,__X_____,
  ____X___,___X____,
  ___X____,___X____,
  ___X____,____X___,
  __X____X,_____X__,
  _X____X_,______X_,
  ______X_,__X_____,
  _____X__,___X____,
  ____X___,___X____,
  ____X___,____X___,
  ___X____,____X___,
  ___XXXXX,XXXXXX__,
  ________,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_5316[ 32] = { /* code 5316 */
  ________,________,
  ____X___,________,
  ____X___,X_______,
  ___X____,X_______,
  ___X____,X____X__,
  ___X____,X___X___,
  __XX____,X__X____,
  __XX____,XXX_____,
  _X_X___X,X_______,
  ___X_XX_,X_______,
  ___X____,X_______,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,X_____X_,
  ___X____,_XXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_538B[ 32] = { /* code 538B */
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  _X______,________,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X______,X_______,
  _X___XXX,XXXXX___,
  _X______,X_X_____,
  _X______,X__X____,
  _X______,X__X____,
  _X______,X___X___,
  _X______,X___X___,
  _X______,X_______,
  _X__XXXX,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_539F[ 32] = { /* code 539F */
  ________,________,
  ________,________,
  _XXXXXXX,XXXXXXX_,
  _X______,X_______,
  _X__XXXX,XXXXXX__,
  _X__X___,_____X__,
  _X__X___,_____X__,
  _X__XXXX,XXXXXX__,
  _X__X___,_____X__,
  _X__X___,_____X__,
  _X___XXX,XXXXX___,
  _X___X__,_X_X____,
  _X___X__,_X__X___,
  _X__X___,_X___X__,
  _X_X____,_X___X__,
  ______XX,X_____X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_53F8[ 32] = { /* code 53F8 */
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  ________,_____X__,
  ________,_____X__,
  __XXXXXX,XXXX_X__,
  ________,_____X__,
  __XXXXXX,XXX__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  __X_____,__X__X__,
  ___XXXXX,XX___X__,
  ________,_____X__,
  ________,_XXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_56FA[ 32] = { /* code 56FA */
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  _X_____X,______X_,
  _X_____X,______X_,
  _X_XXXXX,XXXXX_X_,
  _X_____X,______X_,
  _X_____X,______X_,
  _X__XXXX,XXXX__X_,
  _X__X___,___X__X_,
  _X__X___,___X__X_,
  _X__X___,___X__X_,
  _X__X___,___X__X_,
  _X___XXX,XXXX__X_,
  _X______,______X_,
  __XXXXXX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_5927[ 32] = { /* code 5927 */
  ________,________,
  ________,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,X_______,
  _______X,X_______,
  ______X_,_X______,
  ______X_,_X______,
  _____X__,__X_____,
  _____X__,__X_____,
  ____X___,___X____,
  ___X____,____X___,
  _XX_____,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_5BFC[ 32] = { /* code 5BFC */
  ________,________,
  ________,________,
  __XXXXXX,XXXXX___,
  __X_____,____X___,
  __X_____,____X___,
  __XXXXXX,XXXX__X_,
  __X_____,______X_,
  __XXXXXX,XXXXXXX_,
  ________,___X____,
  ________,___X____,
  _XXXXXXX,XXXXXXX_,
  ____X___,___X____,
  _____X__,___X____,
  ______X_,___X____,
  ________,___X____,
  ________,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_5EA6[ 32] = { /* code 5EA6 */
  ________,________,
  ________,________,
  ________,X_______,
  __XXXXXX,XXXXXXX_,
  _X___X__,___X____,
  _X_XXXXX,XXXXXX__,
  _X___X__,___X____,
  _X___X__,___X____,
  _X____XX,XXXX____,
  _X______,________,
  _X_XXXXX,XXXXX___,
  _X___X__,____X___,
  _X____X_,__XX____,
  _X_____X,XX______,
  _X____XX,_XX_____,
  X_XXXX__,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6001[ 32] = { /* code 6001 */
  ________,________,
  ________,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _______X,X_______,
  ______X_,_X______,
  _____X_X,__X_____,
  ___XX__X,___XX___,
  XXX_____,X____XX_,
  ________,________,
  __X__X__,X___X___,
  __X__X__,X____X__,
  __X__X__,_X_X_X__,
  __X__X__,_X_X__X_,
  _X___X__,___X__X_,
  _X___XXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_603B[ 32] = { /* code 603B */
  ________,________,
  ____X___,___X____,
  ____X___,__X_____,
  _____X__,__X_____,
  _____X__,_X______,
  __XXX_XX,X_XXXX__,
  __X_____,_____X__,
  __X_____,_____X__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  ______X_,________,
  __X_X__X,_____X__,
  __X_X___,X__X_X__,
  _X__X___,X__X__X_,
  _X__X___,X__X__X_,
  _X___XXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6280[ 32] = { /* code 6280 */
  ________,________,
  ________,________,
  ___X____,_X______,
  ___X__XX,XXXXXXX_,
  ___X____,_X______,
  _XXXXX__,_X______,
  ___X____,_X______,
  ___X__XX,XXXXXX__,
  ___X___X,_____X__,
  ___XX__X,____X___,
  __XX____,X___X___,
  _X_X____,_X_X____,
  ___X____,_XX_____,
  ___X____,XX_X____,
  ___X__XX,____X___,
  _XXXXX__,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6377[ 32] = { /* code 6377 */
  ________,________,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X__XX,XXXXXXX_,
  ___X____,__X_____,
  __XXXXXX,XXXXXX__,
  ___X____,__X__X__,
  ___X_XXX,XXXXXXX_,
  ___X____,__X__X__,
  ___X_XXX,XXXXXX__,
  __XXX_X_,__X_____,
  _X_X__X_,__X_____,
  ___X__X_,__XXXX__,
  ___X__XX,__X_____,
  ___X_X__,XXX_____,
  _XXX_X__,__XXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6613[ 32] = { /* code 6613 */
  ________,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  __X_____,_____X__,
  __XXXXXX,XXXXXX__,
  ____X___,________,
  ___XXXXX,XXXXXX__,
  __X____X,__X___X_,
  ______X_,__X___X_,
  ____XX__,_X____X_,
  __XX____,X_____X_,
  _X____XX,_____X__,
  ____XX__,_XX_XX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6709[ 32] = { /* code 6709 */
  ________,________,
  _______X,________,
  ______X_,________,
  _XXXXXXX,XXXXXXX_,
  _____X__,________,
  ____X___,________,
  ___XXXXX,XXXXXX__,
  _XXX____,_____X__,
  X__X____,_____X__,
  ___XXXXX,XXXXXX__,
  ___X____,_____X__,
  ___X____,_____X__,
  ___XXXXX,XXXXXX__,
  ___X____,_____X__,
  ___X____,_____X__,
  ___X____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6C14[ 32] = { /* code 6C14 */
  ________,________,
  ____X___,________,
  ____XXXX,XXXXXX__,
  ___X____,________,
  __X_____,________,
  _X_XXXXX,XXXXX___,
  ________,________,
  __XXXXXX,XXXX____,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,____X___,
  ________,_____XX_,
  ________,_____XX_,
  ________,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6C27[ 32] = { /* code 6C27 */
  ________,________,
  ___X____,________,
  ___X____,________,
  ___XXXXX,XXXXXX__,
  __X_XXXX,XXXXX___,
  _X______,________,
  __XXXXXX,XXXX____,
  ___X____,_X__X___,
  ___X____,X___X___,
  _XXXXXXX,XXXXX___,
  ______X_,____X___,
  __XXXXXX,XXXXX___,
  ______X_,____X___,
  _XXXXXXX,XXXX_XX_,
  ______X_,_____XX_,
  ______X_,_____XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6C28[ 32] = { /* code 6C28 */
  ________,________,
  ____X___,________,
  ___XXXXX,XXXXXX__,
  ___X____,________,
  __XXXXXX,XXXXX___,
  _X______,________,
  __XXXXXX,XXXXX___,
  ______X_,____X___,
  __XXXXXX,XXXXX___,
  _X___X__,___XX___,
  _X___X__,__X_X___,
  __XXXXXX,XXXXX___,
  ___X____,X___X___,
  ____XX__,X___X_X_,
  ______XX,X____XX_,
  _XXXXX__,_XXX_XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6C2E[ 32] = { /* code 6C2E */
  ________,________,
  ________,________,
  ___X____,________,
  ___XXXXX,XXXXX___,
  __X_XXXX,XXXXX___,
  _X_X____,________,
  __XXXXXX,XXXXX___,
  ______X_,____X___,
  ___X__X_,_X__X___,
  ___X__X_,_X__X___,
  _____X_X,X___X___,
  __XXX_X_,_XX_X___,
  ____X_X_,X___X___,
  ___X__X_,X____XX_,
  _____X_X,X____XX_,
  _XXXX___,_XX__XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6E29[ 32] = { /* code 6E29 */
  ________,________,
  ________,________,
  _XX__XXX,XXXXXX__,
  __XX_X__,_____X__,
  ___X_X__,_____X__,
  _____XXX,XXXXXX__,
  _X___X__,_____X__,
  __X__XXX,XXXX_X__,
  ___X____,____X___,
  ___X____,________,
  ___X_XXX,XXXXXX__,
  __X_X__X,__X__X__,
  __X_X__X,__X__X__,
  __X_X__X,__X__X__,
  _X__X__X,__X__X__,
  _X_XXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_6EB6[ 32] = { /* code 6EB6 */
  ________,________,
  ________,________,
  _X______,_X______,
  __X_XXXX,XXXXXXX_,
  ___XX__X,__X___X_,
  ____X_XX,___XX_X_,
  _____X__,_X___X__,
  _XX_____,X_X_____,
  ___X___X,___X____,
  ______X_,____XX__,
  ___XXX__,______X_,
  __X__XXX,XXXXXX__,
  __X__X__,_____X__,
  __X__X__,_____X__,
  _X___X__,_____X__,
  _X____XX,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_7387[ 32] = { /* code 7387 */
  ________,________,
  _______X,________,
  _______X,________,
  _XXXXXXX,XXXXXX__,
  _X_____X,_____X__,
  __X___X_,___XX___,
  ___X__X_,X_X_____,
  ____XXXX,__X_____,
  ___XX__X,___X____,
  __XX__X_,XX__X___,
  _X___XXX,XXX__X__,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_751F[ 32] = { /* code 751F */
  ________,________,
  ________,________,
  ___X____,X_______,
  ___X____,X_______,
  __X_____,X_______,
  __XXXXXX,XXXXXX__,
  __X_____,X_______,
  _X______,X_______,
  _X______,X_______,
  ________,X_______,
  __XXXXXX,XXXXXX__,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  ________,X_______,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_7535[ 32] = { /* code 7535 */
  ________,________,
  _______X,________,
  _______X,________,
  ___XXXXX,XXXX____,
  _XX____X,____XX__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _XXXXXXX,XXXXXX__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _X_____X,_____X__,
  _XXXXXXX,XXXXXX__,
  _______X,________,
  _______X,______X_,
  _______X,______X_,
  _______X,XXXXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_76D0[ 32] = { /* code 76D0 */
  ________,________,
  ____X___,________,
  ____X___,_X______,
  ____X___,_X______,
  __XXXX__,_X_X____,
  ____X___,_X__X___,
  ____X___,_X___X__,
  ____XXX_,_X____X_,
  __XXX___,________,
  ________,________,
  __XXXXXX,XXXXXX__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _X___X__,_X___X__,
  _XXXXXXX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_785D[ 32] = { /* code 785D */
  ________,________,
  ________,________,
  _XXXXX_X,__X___X_,
  ___X___X,__X__X__,
  __X_____,X_X__X__,
  __X_____,__X_X___,
  __XX___X,XXXXXXX_,
  __X_XX_X,______X_,
  _XX__X_X,______X_,
  _XX__X_X,XXXXXXX_,
  __X__X_X,______X_,
  __X__X_X,XXXXXXX_,
  __X__X_X,______X_,
  __X__X_X,______X_,
  __X__X_X,______X_,
  __XXX__X,___XXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_78B1[ 32] = { /* code 78B1 */
  ________,________,
  ________,________,
  ________,____XX__,
  __XXXXXX,XXXXXXX_,
  ___X__X_,____X_X_,
  __X___X_,XXXXX___,
  __X___X_,____X___,
  __XXX_X_,XXX_XX__,
  _XX_X_X_,X_X_XX__,
  X_X_X_X_,X_X_XX__,
  __X_X_X_,X_X_XX__,
  __X_X_X_,X_X_XX__,
  __X_X_X_,X_X_X_X_,
  __X_X_X_,XXX_X_X_,
  __XXXX__,___X_XX_,
  _____X__,__X__XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_795E[ 32] = { /* code 795E */
  ________,________,
  ________,__X_____,
  ___X____,__X_____,
  ____X___,__X_____,
  _XXXXX_X,XXXXXXX_,
  _____X_X,__X___X_,
  ____X__X,__X___X_,
  ____X__X,__X___X_,
  ___XX__X,XXXXXXX_,
  __XX_X_X,__X___X_,
  _X_X__XX,__X___X_,
  ___X___X,__X___X_,
  ___X___X,XXXXXX__,
  ___X____,__X_____,
  ___X____,__X_____,
  ___X____,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_79D1[ 32] = { /* code 79D1 */
  ________,________,
  ________,________,
  _XXXXX__,X____X__,
  ___X____,_X___X__,
  ___X____,__X__X__,
  ___X____,___X_X__,
  _XXXXXXX,____XX__,
  ___XX___,X____X__,
  ___X_X__,_X___X__,
  __XX_X__,__X__X__,
  __XX__X_,_____X__,
  _X_X____,____XXX_,
  ___X__XX,XXXX_X__,
  ___X____,_____X__,
  ___X____,_____X__,
  ___X____,_____X__};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_89E3[ 32] = { /* code 89E3 */
  ________,________,
  ________,________,
  ___XXXX_,XXXXXXX_,
  __X___X_,__X___X_,
  _X___X__,_X____X_,
  XXXXXXXX,_X_X__X_,
  _X__X__X,X___XX__,
  _X__X__X,_X_X____,
  _XXXXXXX,_XXXXXX_,
  _X__X__X,X__X____,
  _X__X__X,X__X____,
  _XXXXXXX,___X____,
  _X__X__X,XXXXXXX_,
  _X__X__X,___X____,
  _X__X__X,___X____,
  X____XX_,___X____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_8FD8[ 32] = { /* code 8FD8 */
  ________,________,
  ________,________,
  __X__XXX,XXXXXXX_,
  __X_____,__X_____,
  ___X____,__X_____,
  ________,_X______,
  _XX_____,_X_X____,
  ___X____,XX__X___,
  ___X____,XX__X___,
  ___X___X,_X___X__,
  ___X__X_,_X___X__,
  ___X_X__,_X____X_,
  ___X____,_X______,
  __X_X___,_X______,
  __X__X__,_X______,
  _X____XX,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_9178[ 32] = { /* code 9178 */
  ________,________,
  ________,__X_____,
  _XXXXXX_,_X__X___,
  ___XX___,_X___X__,
  ___XX___,X_____X_,
  _XXXXXX_,XXXXXXX_,
  _X_XX_X_,_X__X___,
  _XX_X_X_,X____X__,
  _XX_X_XX,_X____X_,
  _XX_X_X_,_XXXXX__,
  _XX__XX_,XX___X__,
  _X____X_,XX___X__,
  _XXXXXXX,__X_X___,
  _X____X_,___X____,
  _X____X_,__X_X___,
  _XXXXXXX,XX___XX_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_94F5[ 32] = { /* code 94F5 */
  ________,________,
  ________,_X______,
  __X_____,__X_____,
  __XXXXXX,XXXXXXX_,
  _X____X_,__X___X_,
  _X____X_,_X____X_,
  _XXXX_X_,_X______,
  ___X_XXX,XXXXXXX_,
  ___X____,X___X___,
  _XXXXX__,X___X___,
  ___X___X,____X___,
  ___X____,X__X____,
  ___X____,_XXX____,
  ___X_X__,__XXX___,
  ___XX___,XX___X__,
  ______XX,______X_};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan16_9650[ 32] = { /* code 9650 */
  ________,________,
  ________,________,
  _XXXX_XX,XXXXXX__,
  _X__X_X_,_____X__,
  _X__X_X_,_____X__,
  _X__X_XX,XXXXXX__,
  _X_X__X_,_____X__,
  _X__X_X_,_____X__,
  _X__X_XX,XXXXXX__,
  _X__X_X_,_X______,
  _X__X_X_,_X___X__,
  _XXXX_X_,__X_X___,
  _X____X_,__XX____,
  _X____X_,___X____,
  _X____X_,____X___,
  _X____XX,XX___XX_};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan16_CharInfo[36] = {
   {  16,  16,  2, acGUI_Fontyouyuan16_4F4D } /* code 4F4D */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_4F53 } /* code 4F53 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_516C } /* code 516C */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_5316 } /* code 5316 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_538B } /* code 538B */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_539F } /* code 539F */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_53F8 } /* code 53F8 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_56FA } /* code 56FA */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_5927 } /* code 5927 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_5BFC } /* code 5BFC */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_5EA6 } /* code 5EA6 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6001 } /* code 6001 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_603B } /* code 603B */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6280 } /* code 6280 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6377 } /* code 6377 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6613 } /* code 6613 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6709 } /* code 6709 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6C14 } /* code 6C14 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6C27 } /* code 6C27 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6C28 } /* code 6C28 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6C2E } /* code 6C2E */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6E29 } /* code 6E29 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_6EB6 } /* code 6EB6 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_7387 } /* code 7387 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_751F } /* code 751F */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_76D0 } /* code 76D0 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_785D } /* code 785D */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_78B1 } /* code 78B1 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_795E } /* code 795E */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_79D1 } /* code 79D1 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_89E3 } /* code 89E3 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_8FD8 } /* code 8FD8 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_9178 } /* code 9178 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_94F5 } /* code 94F5 */
  ,{  16,  16,  2, acGUI_Fontyouyuan16_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop35 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 35] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop34 = {
   0x94F5 /* first character */
  ,0x94F5 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop33 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop32 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop31 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop30 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop29 = {
   0x795E /* first character */
  ,0x795E /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop28 = {
   0x78B1 /* first character */
  ,0x78B1 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop27 = {
   0x785D /* first character */
  ,0x785D /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop26 = {
   0x76D0 /* first character */
  ,0x76D0 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop24 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop23 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop22 = {
   0x6EB6 /* first character */
  ,0x6EB6 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop21 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop20 = {
   0x6C2E /* first character */
  ,0x6C2E /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop19 = {
   0x6C27 /* first character */
  ,0x6C28 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop18 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop17 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop16 = {
   0x6613 /* first character */
  ,0x6613 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop15 = {
   0x6377 /* first character */
  ,0x6377 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop14 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop13 = {
   0x603B /* first character */
  ,0x603B /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop12 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop11 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop10 = {
   0x5BFC /* first character */
  ,0x5BFC /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  9] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop9 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  8] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop8 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  7] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop7 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop6 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop5 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop4 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan16_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontyouyuan16_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

