/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: youyuan20.c                                           *
* Font:        свт╡                                                  *
* Height:      20                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  20                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Downloads\en.stm32cubef4\STM32Cube_FW_F4_V1.21.0\Middlewares\ST\STemWin\Software\hanzi.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan20;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_4F4D[ 60] = { /* code 4F4D */
  ________,________,________,
  ________,___X____,________,
  ____X___,___X____,________,
  ____X___,____X___,________,
  ____X_XX,XXXXXXXX,XXX_____,
  ___X____,________,________,
  ___X____,________,X_______,
  __XX___X,________,X_______,
  __XX____,X_______,X_______,
  _X_X____,X_______,X_______,
  XX_X____,X______X,________,
  ___X____,X______X,________,
  ___X____,_X_____X,________,
  ___X____,_X_____X,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  ___X____,_____X__,________,
  ___X_XXX,XXXXXXXX,XXX_____,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_4F53[ 60] = { /* code 4F53 */
  ________,________,________,
  ________,___X____,________,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ____X___,___X____,________,
  ___X__XX,XXXXXXXX,XXX_____,
  ___X____,___XX___,________,
  ___X____,__XXX___,________,
  __XX____,__XXXX__,________,
  _XXX____,_XXX_X__,________,
  _X_X____,_X_X__X_,________,
  ___X____,X__X__XX,________,
  ___X___X,X__X___X,________,
  ___X___X,___X____,X_______,
  ___X__X_,___X____,_X______,
  ___XXX_X,XXXXXXXX,__X_____,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X____,___X____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_516C[ 60] = { /* code 516C */
  ________,________,________,
  ________,________,________,
  _______X,____X___,________,
  ______X_,____XX__,________,
  ______X_,_____X__,________,
  _____X__,______X_,________,
  ____XX__,______X_,________,
  ____X___,_______X,________,
  ___X____,_X______,X_______,
  __X_____,X_______,_X______,
  _X______,X_______,__X_____,
  _______X,_____X__,________,
  _______X,______X_,________,
  ______X_,______X_,________,
  _____X__,_______X,________,
  _____X__,_______X,________,
  ____X___,________,X_______,
  ___XX__X,XXXXXXXX,X_______,
  ____XXX_,________,_X______,
  ________,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_5316[ 60] = { /* code 5316 */
  ________,________,________,
  _____X__,________,________,
  _____X__,___X____,________,
  _____X__,___X____,________,
  ____X___,___X____,_X______,
  ____X___,___X____,X_______,
  ____X___,___X___X,________,
  ___X____,___X_XX_,________,
  __XX____,___XXX__,________,
  __XX____,__XX____,________,
  _X_X____,_XXX____,________,
  ___X__XX,X__X____,________,
  ___X__X_,___X____,________,
  ___X____,___X____,__X_____,
  ___X____,___X____,__X_____,
  ___X____,___X____,__X_____,
  ___X____,___X____,__X_____,
  ___X____,___X____,__X_____,
  ___X____,___X____,_X______,
  ________,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_538B[ 60] = { /* code 538B */
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,XX______,
  __X_____,________,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  __X__XXX,XXXXXXXX,X_______,
  __X_____,__X_____,________,
  __X_____,__X__X__,________,
  __X_____,__X__XX_,________,
  __X_____,__X___X_,________,
  __X_____,__X____X,________,
  __X_____,__X____X,________,
  __X_____,__X_____,________,
  _X______,__X_____,________,
  _X__XXXX,XXXXXXXX,XXX_____,
  _X______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_539F[ 60] = { /* code 539F */
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __X_____,__X_____,________,
  __X_____,__X_____,________,
  __X__XXX,XXXXXXXX,XX______,
  __X__X__,________,_X______,
  __X__X__,________,_X______,
  __X__XXX,XXXXXXXX,XX______,
  __X__X__,________,_X______,
  __X__X__,________,_X______,
  __X__X__,________,_X______,
  __X__XXX,XXXXXXXX,X_______,
  __X____X,___X__X_,________,
  __X____X,___X__XX,________,
  __X___X_,___X___X,X_______,
  _X___X__,___X____,X_______,
  _X__XX__,___X____,_X______,
  _X_XX__X,___X____,_XX_____,
  _X______,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_53F8[ 60] = { /* code 53F8 */
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XX______,
  ________,________,_X______,
  ________,________,_X______,
  _XXXXXXX,XXXXXXXX,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,________,_X______,
  __XXXXXX,XXXXXX__,_X______,
  __X_____,_____X__,_X______,
  __X_____,_____X__,_X______,
  __X_____,_____X__,_X______,
  __X_____,_____X__,_X______,
  __X_____,_____X__,_X______,
  ___XXXXX,XXXXXX__,_X______,
  ________,________,_X______,
  ________,________,_X______,
  ________,___XXX__,_X______,
  ________,______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_56FA[ 60] = { /* code 56FA */
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,XX______,
  __X_____,_X______,_X______,
  __X_____,_X______,_X______,
  __X_____,_X______,_X______,
  __X_XXXX,XXXXXXXX,XX______,
  __X_____,_X______,_X______,
  __X_____,_X______,_X______,
  __X_____,_X______,_X______,
  __X__XXX,XXXXXXX_,_X______,
  __X__X__,______X_,_X______,
  __X__X__,______X_,_X______,
  __X__X__,______X_,_X______,
  __X__X__,______X_,_X______,
  __X__X__,______X_,_X______,
  __X___XX,XXXXXX__,_X______,
  __X_____,________,_X______,
  __XXXXXX,XXXXXXXX,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_5927[ 60] = { /* code 5927 */
  ________,________,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,_X______,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,X_XX____,________,
  ________,X__X____,________,
  ________,X__X____,________,
  _______X,____X___,________,
  ______XX,_____X__,________,
  ______X_,_____XX_,________,
  _____X__,______X_,________,
  ___XX___,_______X,X_______,
  __XX____,________,XX______,
  _X______,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_5BFC[ 60] = { /* code 5BFC */
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___X____,_______X,________,
  ___X____,_______X,________,
  ___XXXXX,XXXXXXXX,________,
  ___X____,________,________,
  ___X____,________,__X_____,
  ___X____,________,_X______,
  ___XXXXX,XXXXXXXX,XX______,
  ________,______X_,________,
  ________,______X_,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _____X__,______X_,________,
  ______X_,______X_,________,
  _______X,______X_,________,
  ________,X_____X_,________,
  ________,X_____X_,________,
  ________,__XXX_X_,________,
  ________,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_5EA6[ 60] = { /* code 5EA6 */
  ________,________,________,
  ________,_X______,________,
  ________,__X_____,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __X____X,______X_,________,
  __X____X,______X_,________,
  __XXXXXX,XXXXXXXX,XX______,
  __X____X,______X_,________,
  __X____X,______X_,________,
  __X____X,XXXXXXX_,________,
  __X_____,________,________,
  __X_____,________,________,
  __X_XXXX,XXXXXXXX,X_______,
  __X___X_,_______X,________,
  __X____X,______X_,________,
  __X_____,XX__XX__,________,
  __X_____,_XXX____,________,
  _X_____X,XX_XX___,________,
  _X__XXX_,_____XXX,________,
  __XX____,________,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6001[ 60] = { /* code 6001 */
  ________,________,________,
  ________,________,________,
  ________,_X______,________,
  ________,_X______,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,X_XX____,________,
  _______X,X__XX___,________,
  ______XX,_X__XX__,________,
  _____X__,_X____X_,________,
  __XXX___,__X____X,XX______,
  _X______,__X_____,__X_____,
  ________,_X______,________,
  ___X__X_,__X____X,________,
  ___X__X_,__X_____,X_______,
  ___X__X_,___X____,X_______,
  __X___X_,___X__X_,_X______,
  __X___X_,___XX_X_,_X______,
  __X___X_,______X_,__X_____,
  _X____XX,_____XX_,__X_____,
  _______X,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_603B[ 60] = { /* code 603B */
  ________,________,________,
  _____X__,______X_,________,
  _____X__,_____X__,________,
  ______X_,_____X__,________,
  ______XX,____X___,________,
  ___XXXXX,XXXXXXXX,________,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ________,________,________,
  _____X__,_X______,X_______,
  __X__X__,_XX_____,XX______,
  __X__X__,__X___X_,_X______,
  __X__X__,__X___X_,_XX_____,
  _XX__X__,______X_,__X_____,
  _X____X_,______X_,__X_____,
  ______XX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6280[ 60] = { /* code 6280 */
  ________,________,________,
  ________,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X__X,XXXXXXXX,XXX_____,
  ____X___,____X___,________,
  _XXXXXX_,____X___,________,
  ____X___,____X___,________,
  ____X__X,XXXXXXXX,XX______,
  ____X___,X_______,_X______,
  ____X_X_,_X______,X_______,
  ____XX__,_X______,X_______,
  __XXX___,__X____X,________,
  _XX_X___,___X__X_,________,
  ____X___,___XXXX_,________,
  ____X___,____XX__,________,
  ____X___,__XX_XX_,________,
  ____X___,XXX____X,________,
  _X__X_XX,X_______,XX______,
  __XX_X__,________,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6377[ 60] = { /* code 6377 */
  ________,________,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X__X,XXXXXXXX,XX______,
  ____X___,____X___,________,
  _XXXXXX_,____X___,________,
  ____X__X,XXXXXXXX,XX______,
  ____X___,____X___,_X______,
  ____X_XX,XXXXXXXX,XXX_____,
  ____X___,____X___,_X______,
  ____X___,____X___,_X______,
  ____X_XX,XXXXXXXX,X_______,
  ___XXX__,X___X___,________,
  _XX_X___,X___X___,________,
  ____X___,X___XXXX,XXX_____,
  ____X___,X___X___,________,
  ____X__X,_X__X___,________,
  ____X__X,__XXX___,________,
  _XXXX_X_,____XXX_,________,
  ________,_______X,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6613[ 60] = { /* code 6613 */
  ________,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,X_______,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ___X____,________,X_______,
  ___X____,________,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ______X_,________,________,
  _____X__,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ___X____,XX___X__,_X______,
  _XX____X,X____X__,_X______,
  ______XX,____X___,_X______,
  _____X__,___X____,_X______,
  __XXX___,_XX_____,_X______,
  _X______,XX______,_X______,
  ______XX,___XX___,XX______,
  ____XX__,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6709[ 60] = { /* code 6709 */
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _______X,________,________,
  ______X_,________,________,
  _____X__,________,________,
  ____XXXX,XXXXXXXX,X_______,
  __XXX___,________,X_______,
  XX__X___,________,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,____XX__,X_______,
  ____X___,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6C14[ 60] = { /* code 6C14 */
  ________,________,________,
  _____X__,________,________,
  _____X__,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ___X____,________,________,
  __X_____,________,________,
  _X__XXXX,XXXXXXXX,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,________,X_______,
  ________,________,X_______,
  ________,________,X_______,
  ________,________,X_X_____,
  ________,________,X_X_____,
  ________,________,X_X_____,
  ________,________,X_X_____,
  ________,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6C27[ 60] = { /* code 6C27 */
  ________,________,________,
  ____X___,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ___X____,________,________,
  __XX_XXX,XXXXXXXX,X_______,
  _XX_____,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXXX,________,
  ____X___,___X___X,________,
  _____X__,___X___X,________,
  _XXXXXXX,XXXXXXXX,________,
  ________,X_______,X_______,
  ________,X_______,X_______,
  __XXXXXX,XXXXXX__,X_______,
  ________,X_______,X_X_____,
  _XXXXXXX,XXXXXXX_,X_X_____,
  ________,X_______,X_X_____,
  ________,X_______,_XX_____,
  ________,X_______,_XX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6C28[ 60] = { /* code 6C28 */
  ________,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ___X____,________,________,
  __X_XXXX,XXXXXXXX,X_______,
  _X______,________,________,
  __XXXXXX,XXXXXXXX,________,
  _______X,_______X,________,
  ___XXXXX,XXXXX__X,________,
  __X_____,_____XXX,________,
  __X___X_,_____X_X,________,
  __X___X_,_____X_X,________,
  __XXXXXX,XXXXXXX_,X_______,
  _____X__,___X____,X_______,
  ____XX__,__XX____,X_X_____,
  ______XX,_XX_____,X_X_____,
  ________,XXX_____,X_X_____,
  ___XXXXX,___XXX__,XXX_____,
  _XX_____,________,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6C2E[ 60] = { /* code 6C2E */
  ________,________,________,
  _____X__,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ___X____,________,________,
  __X_XXXX,XXXXXXXX,________,
  _X______,________,________,
  __XXXXXX,XXXXXXX_,________,
  ________,_______X,________,
  _____X__,X___X__X,________,
  ____X___,X___X__X,________,
  ____X__X,___X___X,________,
  ___X___X,XXX____X,________,
  ____XXX_,__XXX___,X_______,
  __XX_X__,X__XXX__,X_X_____,
  _____X__,X__X____,X_X_____,
  ____X___,X_X_____,X_X_____,
  _______X,_XX_____,X_X_____,
  _____XX_,___XX___,_XX_____,
  __XXX___,_____X__,_X______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6E29[ 60] = { /* code 6E29 */
  ________,________,________,
  ________,________,________,
  __X____X,XXXXXXXX,X_______,
  ___X__X_,________,X_______,
  ____X_X_,________,X_______,
  ____X_XX,XXXXXXXX,X_______,
  _X____X_,________,X_______,
  _XX___X_,________,X_______,
  __XX__X_,________,X_______,
  ___XX__X,XXXXXXXX,X_______,
  ________,________,________,
  ____X___,________,________,
  ____X_XX,XXXXXXXX,XX______,
  ___X__X_,_X___X__,_X______,
  ___X__X_,_X___X__,_X______,
  ___X__X_,_X___X__,_X______,
  __X___X_,_X___X__,_X______,
  __X___X_,_X___X__,_X______,
  _X____X_,_X___X__,_X______,
  _X___XXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_6EB6[ 60] = { /* code 6EB6 */
  ________,________,________,
  ________,___X____,________,
  _X______,___X____,________,
  __X___XX,XXXXXXXX,XX______,
  ___X_X__,________,__X_____,
  ____XX__,_X___XX_,__X_____,
  _____X__,X_____XX,__X_____,
  _______X,___XX___,X_______,
  _XX___X_,__X_XX__,_X______,
  __XX____,_X___XX_,________,
  ____X___,XX____XX,________,
  _______X,________,X_______,
  ____X_X_,________,_XX_____,
  ___X_X_X,XXXXXXXX,X_______,
  ___X___X,________,_X______,
  ___X___X,________,_X______,
  __X____X,________,_X______,
  __X____X,________,_X______,
  _X_____X,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_7387[ 60] = { /* code 7387 */
  ________,________,________,
  ________,_X______,________,
  ________,_X______,________,
  __XXXXXX,XXXXXXXX,XX______,
  ________,_X______,________,
  __X_____,X_______,XX______,
  ___X____,X__X__XX,________,
  ____X__X,__X_XX__,________,
  _______X,XXX_____,________,
  _____X__,_X___X__,________,
  ____X___,X__X__X_,________,
  ___X___X,X__XX__X,________,
  _XX___XX,XXXXX___,X_______,
  ________,_X___X__,________,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_751F[ 60] = { /* code 751F */
  ________,________,________,
  ________,________,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  ___XXXXX,XXXXXXXX,XX______,
  ___X____,__X_____,________,
  __X_____,__X_____,________,
  _XX_____,__X_____,________,
  _X______,__X_____,________,
  ________,__X_____,________,
  ___XXXXX,XXXXXXXX,XX______,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_7535[ 60] = { /* code 7535 */
  ________,________,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  __XXXXXX,XXXXXXXX,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __X_____,_X______,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  ________,_X______,__X_____,
  ________,_X______,__X_____,
  ________,_X______,__X_____,
  ________,_XXXXXXX,XX______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_76D0[ 60] = { /* code 76D0 */
  ________,________,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  _____X__,____X___,________,
  __XXXXXX,X___X___,________,
  _____X__,____X_XX,________,
  _____X__,____X___,X_______,
  _____X__,____X___,_X______,
  _____X_X,X___X___,_XX_____,
  _____XX_,____X___,________,
  _XXXX___,____X___,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,X_______,
  __X____X,____X___,_X______,
  __X____X,____X___,_X______,
  __X____X,____X___,_X______,
  __X____X,____X___,_X______,
  __X____X,____X___,_X______,
  __X____X,____X___,_X______,
  _XXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_785D[ 60] = { /* code 785D */
  ________,________,________,
  ________,_____X__,________,
  _XXXXXX_,_X___X__,_X______,
  ____X___,_X___X__,_X______,
  ___X____,__X__X__,X_______,
  ___X____,__X__X__,X_______,
  ___X____,_____X__,________,
  ___X____,_XXXXXXX,XX______,
  __XXXXX_,_X______,_X______,
  __XX__X_,_X______,_X______,
  __XX__X_,_XXXXXXX,XX______,
  _X_X__X_,_X______,_X______,
  ___X__X_,_X______,_X______,
  ___X__X_,_X______,_X______,
  ___X__X_,_XXXXXXX,XX______,
  ___X__X_,_X______,_X______,
  ___X__X_,_X______,_X______,
  ___X__X_,_X______,_X______,
  ___XXXX_,_X____X_,_X______,
  ________,_X_____X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_78B1[ 60] = { /* code 78B1 */
  ________,________,________,
  ________,________,________,
  ________,_______X,_X______,
  _XXXXXX_,XXXXXXXX,XX______,
  ____X___,X______X,__X_____,
  ___X____,X______X,__X_____,
  ___X____,X_XXXX_X,________,
  ___X____,X______X,_X______,
  __XXXX__,X_XXXX_X,_X______,
  __X___X_,X_X__X_X,_X______,
  _XX___X_,X_X__X_X,_X______,
  _XX___X_,X_X__X_X,_X______,
  X_X___X_,X_X__X_X,_X______,
  __X___X_,X_X__X_X,X_______,
  __X___X_,X_X__X_X,X_______,
  __X___X_,X_X__X_X,X_X_____,
  __X___XX,__XXXX_X,X_X_____,
  __X__XXX,______X_,X_X_____,
  ___XXX_X,_____X__,_XX_____,
  ______X_,____X___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_795E[ 60] = { /* code 795E */
  ________,________,________,
  ___X____,_____X__,________,
  ____X___,_____X__,________,
  _____X__,_____X__,________,
  __XXXX__,_XXXXXXX,XX______,
  ______X_,_X___X__,_X______,
  ______X_,_X___X__,_X______,
  ______X_,_X___X__,_X______,
  _____X__,_X___X__,_X______,
  ____XX__,_XXXXXXX,XX______,
  ___XXX__,_X___X__,_X______,
  __XXX_X_,_X___X__,_X______,
  _XX_X__X,_X___X__,_X______,
  _X__X___,_X___X__,_X______,
  ____X___,_XXXXXXX,_X______,
  ____X___,_____X__,X_______,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________,
  ____X___,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_79D1[ 60] = { /* code 79D1 */
  ________,________,________,
  ________,________,________,
  __XXXXXX,__XX____,X_______,
  ____X___,___XX___,X_______,
  ____X___,____X___,X_______,
  ____X___,_____X__,X_______,
  ____X___,______X_,X_______,
  _XXXXXXX,_X_____X,X_______,
  ____XX__,__X_____,X_______,
  ____X_X_,___X____,X_______,
  ___XX_XX,____X___,X_______,
  ___XX__X,_____X__,X_______,
  __X_X___,X_______,X_______,
  __X_X___,________,X_X_____,
  _X__X___,_XXXXXXX,XX______,
  ____X___,X_______,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______,
  ____X___,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_89E3[ 60] = { /* code 89E3 */
  ________,________,________,
  ____X___,________,________,
  ____XXXX,X_XXXXXX,XX______,
  ___X____,X____X__,_X______,
  __X____X,____X___,_X______,
  _XX___X_,____X___,_X______,
  XXXXXXXX,X__X_XXX,XX______,
  __X__X__,_XX_____,________,
  __X__X__,_X_X__X_,________,
  __X__X__,_X_X__X_,________,
  __XXXXXX,XX_XXXXX,XXX_____,
  __X__X__,_XX___X_,________,
  __X__X__,_XX___X_,________,
  __X__X__,_X____X_,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __X__X__,_X____X_,________,
  __X__X__,_X____X_,________,
  _X___X__,_X____X_,________,
  _X____XX,XX____X_,________,
  _X______,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_8FD8[ 60] = { /* code 8FD8 */
  ________,________,________,
  ________,________,________,
  __X____X,XXXXXXXX,XX______,
  ___X____,_____X__,________,
  ___XX___,_____X__,________,
  ____X___,____X___,________,
  ________,____X___,________,
  _XXX____,___XX_X_,________,
  ____X___,___XX_XX,________,
  ____X___,__X_X__X,________,
  ____X___,_XX_X___,X_______,
  ____X___,_X__X___,X_______,
  ____X___,X___X___,_X______,
  ____X__X,____X___,_X______,
  ____X_X_,____X___,__X_____,
  ____X___,____X___,________,
  ___X_X__,____X___,________,
  __X___X_,____X___,________,
  _X_____X,XXXXXXXX,XXX_____,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_9178[ 60] = { /* code 9178 */
  ________,________,________,
  ________,________,________,
  _XXXXXXX,X___X___,________,
  ___X__X_,____X___,X_______,
  ___X__X_,___X____,_X______,
  __XXXXXX,__X____X,XX______,
  _XXX__X_,X_XXXXX_,__X_____,
  _X_X__X_,X__X___X,________,
  _X_X__X_,X_XX____,XX______,
  _X_X__X_,X_X_____,_XX_____,
  _X_X__X_,XX__X___,__X_____,
  _X_X__X_,X__XXXXX,XX______,
  _X_X___X,X__X____,X_______,
  _XX_____,X_X_X___,X_______,
  _X______,XX__X__X,X_______,
  _XXXXXXX,X____X_X,________,
  _X______,X____XX_,________,
  _X______,X___XXXX,________,
  _XXXXXXX,X_XX____,XX______,
  ________,_X______,__X_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_94F5[ 60] = { /* code 94F5 */
  ________,________,________,
  ___X____,____X___,________,
  ___X____,____X___,________,
  __XXXXX_,XXXXXXXX,XX______,
  __X_____,X_______,__X_____,
  __X_____,X___X___,__X_____,
  _X______,X___X___,_X______,
  ________,____X___,________,
  _XXXXXX_,___X____,________,
  ____X___,XXXXXXXX,XXX_____,
  ____X___,__X_____,X_______,
  _XXXXXX_,__X____X,________,
  ____X___,_X_____X,________,
  ____X___,_XX____X,________,
  ____X___,___XX_X_,________,
  ____X___,_____XX_,________,
  ____X_X_,____X_XX,________,
  ____XX__,___X____,X_______,
  ____X___,XXX_____,_X______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan20_9650[ 60] = { /* code 9650 */
  ________,________,________,
  ________,________,________,
  __XXXX__,XXXXXXXX,X_______,
  _X___X__,X_______,X_______,
  _X___X__,X_______,X_______,
  _X___X__,X_______,X_______,
  _X___X__,XXXXXXXX,X_______,
  _X__X___,X_______,X_______,
  _X__X___,X_______,X_______,
  _X___X__,X_______,X_______,
  _X___X__,XXXXXXXX,X_______,
  _X____X_,X__X____,________,
  _X____X_,X___X___,_X______,
  _X____X_,X___X__X,X_______,
  _XXXXX__,X___XXXX,________,
  _X______,X____X__,________,
  _X______,X_____X_,________,
  _X______,X______X,X_______,
  _X______,X_XXX___,XX______,
  ________,XX______,__X_____};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan20_CharInfo[36] = {
   {  20,  20,  3, acGUI_Fontyouyuan20_4F4D } /* code 4F4D */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_4F53 } /* code 4F53 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_516C } /* code 516C */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_5316 } /* code 5316 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_538B } /* code 538B */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_539F } /* code 539F */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_53F8 } /* code 53F8 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_56FA } /* code 56FA */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_5927 } /* code 5927 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_5BFC } /* code 5BFC */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_5EA6 } /* code 5EA6 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6001 } /* code 6001 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_603B } /* code 603B */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6280 } /* code 6280 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6377 } /* code 6377 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6613 } /* code 6613 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6709 } /* code 6709 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6C14 } /* code 6C14 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6C27 } /* code 6C27 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6C28 } /* code 6C28 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6C2E } /* code 6C2E */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6E29 } /* code 6E29 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_6EB6 } /* code 6EB6 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_7387 } /* code 7387 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_751F } /* code 751F */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_7535 } /* code 7535 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_76D0 } /* code 76D0 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_785D } /* code 785D */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_78B1 } /* code 78B1 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_795E } /* code 795E */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_79D1 } /* code 79D1 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_89E3 } /* code 89E3 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_8FD8 } /* code 8FD8 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_9178 } /* code 9178 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_94F5 } /* code 94F5 */
  ,{  20,  20,  3, acGUI_Fontyouyuan20_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop35 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 35] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop34 = {
   0x94F5 /* first character */
  ,0x94F5 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop33 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop32 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop31 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop30 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop29 = {
   0x795E /* first character */
  ,0x795E /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop28 = {
   0x78B1 /* first character */
  ,0x78B1 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop27 = {
   0x785D /* first character */
  ,0x785D /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop26 = {
   0x76D0 /* first character */
  ,0x76D0 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop24 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop23 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop22 = {
   0x6EB6 /* first character */
  ,0x6EB6 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop21 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop20 = {
   0x6C2E /* first character */
  ,0x6C2E /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop19 = {
   0x6C27 /* first character */
  ,0x6C28 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop18 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop17 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop16 = {
   0x6613 /* first character */
  ,0x6613 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop15 = {
   0x6377 /* first character */
  ,0x6377 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop14 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop13 = {
   0x603B /* first character */
  ,0x603B /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop12 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop11 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop10 = {
   0x5BFC /* first character */
  ,0x5BFC /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  9] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop9 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  8] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop8 = {
   0x56FA /* first character */
  ,0x56FA /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  7] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop7 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop6 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop5 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop4 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan20_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontyouyuan20_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan20_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan20 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,20 /* height of font  */
  ,20 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan20_Prop1}
  ,17 /* Baseline */
  ,9 /* Height of lowercase characters */
  ,13 /* Height of capital characters */
};

