/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.40                      *
*        Compiled Mar 17 2017, 15:34:36                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: youyuan18.c                                           *
* Font:        свт╡                                                  *
* Height:      18                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  18                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\Administrator\Downloads\en.stm32cubef4\STM32Cube_FW_F4_V1.21.0\Middlewares\ST\STemWin\Software\hanzi.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan18;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_4F4D[ 54] = { /* code 4F4D */
  ________,________,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ___X____,___X____,________,
  ___X__XX,XXX_XXXX,________,
  ___X____,________,________,
  __XX__X_,______X_,________,
  __XX___X,______X_,________,
  _X_X___X,______X_,________,
  X__X___X,______X_,________,
  ___X____,X____X__,________,
  ___X____,X____X__,________,
  ___X____,X____X__,________,
  ___X____,X____X__,________,
  ___X____,X___X___,________,
  ___X____,____X___,________,
  ___XXXXX,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_4F53[ 54] = { /* code 4F53 */
  ________,________,________,
  ____X___,__X_____,________,
  ____X___,__X_____,________,
  ___X____,__X_____,________,
  ___X_XXX,XXXXXXXX,X_______,
  ___X____,__X_____,________,
  __XX____,_XXX____,________,
  __XX____,_XXX____,________,
  _X_X____,X_X_X___,________,
  XX_X____,X_X__X__,________,
  ___X___X,__X__X__,________,
  ___X__X_,__X___X_,________,
  ___X_X__,__X____X,________,
  ___XX__X,XXXXXX__,X_______,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  ___X____,__X_____,________,
  ________,__X_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_516C[ 54] = { /* code 516C */
  ________,________,________,
  ______X_,___X____,________,
  ______X_,___X____,________,
  _____X__,___XX___,________,
  _____X__,____X___,________,
  ____X___,_____X__,________,
  ___X____,_____XX_,________,
  __X_____,X_____XX,________,
  _X_____X,_______X,X_______,
  X______X,________,X_______,
  ______X_,____X___,________,
  ______X_,_____X__,________,
  _____X__,_____X__,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ___X__XX,XXXXXXXX,________,
  ____XX__,_______X,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_5316[ 54] = { /* code 5316 */
  ________,________,________,
  ________,________,________,
  ____X___,_X______,________,
  ____X___,_X_____X,________,
  ____X___,_X____XX,________,
  ___X____,_X___XX_,________,
  ___X____,_X__X___,________,
  __XX____,_X_X____,________,
  _X_X____,_XX_____,________,
  _X_X___X,XX______,________,
  ___X_XX_,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,X_______,
  ___X____,_X______,X_______,
  ___X____,_X______,X_______,
  ___X____,_X______,X_______,
  ___X____,__XXXXXX,________,
  ___X____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_538B[ 54] = { /* code 538B */
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXXX,________,
  __X_____,________,________,
  __X_____,_X______,________,
  __X_____,_X______,________,
  __X_____,_X______,________,
  __X_____,_X______,________,
  __X_XXXX,XXXXXXXX,________,
  __X_____,_X______,________,
  __X_____,_X__X___,________,
  __X_____,_X__XX__,________,
  __X_____,_X___X__,________,
  __X_____,_X____X_,________,
  _X______,_X____X_,________,
  _X______,_X______,________,
  _X_XXXXX,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_539F[ 54] = { /* code 539F */
  ________,________,________,
  __XXXXXX,XXXXXXXX,X_______,
  _X______,_X______,________,
  _X______,_X______,________,
  _X___XXX,XXXXXXXX,________,
  _X__X___,_______X,________,
  _X__X___,_______X,________,
  _X__XXXX,XXXXXXXX,________,
  _X__X___,_______X,________,
  _X__X___,_______X,________,
  _X___XXX,XXXXXXXX,________,
  _X______,__X_____,________,
  _X____X_,__X__X__,________,
  _X___X__,__X___X_,________,
  _X___X__,__X___XX,________,
  _X__X___,__X____X,________,
  _X_X__XX,__X_____,X_______,
  ________,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_53F8[ 54] = { /* code 53F8 */
  ________,________,________,
  __XXXXXX,XXXXXXX_,________,
  ________,_______X,________,
  ________,_______X,________,
  _XXXXXXX,XXXXXX_X,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,_______X,________,
  __XXXXXX,XXXXX__X,________,
  __X_____,____X__X,________,
  __X_____,____X__X,________,
  __X_____,____X__X,________,
  __X_____,____X__X,________,
  __XXXXXX,XXXXX__X,________,
  ________,_______X,________,
  ________,_______X,________,
  ________,__XXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_5927[ 54] = { /* code 5927 */
  ________,________,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ________,XX______,________,
  ________,XX______,________,
  _______X,__X_____,________,
  _______X,__X_____,________,
  _______X,___X____,________,
  ______X_,___X____,________,
  _____X__,____X___,________,
  ____XX__,_____X__,________,
  ___X____,______X_,________,
  _XX_____,_______X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_5BFC[ 54] = { /* code 5BFC */
  ________,________,________,
  ___XXXXX,XXXXXX__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___X____,_____X__,________,
  ___XXXXX,XXXXX___,X_______,
  ___X____,________,X_______,
  ___X____,_______X,X_______,
  ___XXXXX,XXXXXXXX,________,
  ________,_____X__,________,
  XXXXXXXX,XXXXXXXX,X_______,
  ________,_____X__,________,
  _____X__,_____X__,________,
  ______X_,_____X__,________,
  _______X,_____X__,________,
  ________,_____X__,________,
  ________,_XXXXX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_5EA6[ 54] = { /* code 5EA6 */
  ________,________,________,
  ________,X_______,________,
  ___XXXXX,XXXXXXXX,X_______,
  __X___X_,____X___,________,
  __X___X_,____X___,________,
  __XXXXXX,XXXXXXXX,________,
  __X___X_,____X___,________,
  __X___X_,____X___,________,
  __X___XX,XXXXX___,________,
  __X_____,________,________,
  __X_XXXX,XXXXXX__,________,
  __X__X__,______X_,________,
  __X___X_,_____X__,________,
  _X_____X,___XX___,________,
  _X______,XXX_____,________,
  _X_____X,X_XX____,________,
  _X_XXXX_,____XXXX,________,
  __X_____,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6001[ 54] = { /* code 6001 */
  ________,________,________,
  ________,________,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,XX______,________,
  _______X,__X_____,________,
  ______X_,X__XX___,________,
  ____XX__,X___XX__,________,
  _XXX____,_X____XX,X_______,
  ________,________,________,
  ________,X_______,________,
  ___X_X__,_X____X_,________,
  __X__X__,_X_____X,________,
  __X__X__,__X__X_X,________,
  __X__X__,__X__X_X,________,
  _X___X__,_____X__,X_______,
  _X____XX,XXXXX___,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_603B[ 54] = { /* code 603B */
  ________,________,________,
  ____X___,____X___,________,
  _____X__,____X___,________,
  ______X_,___X____,________,
  ___XXXXX,XXXXXX__,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  _____X__,X_____X_,________,
  __X__X__,X______X,________,
  __X__X__,_X___X_X,________,
  __X__X__,_X___X__,X_______,
  _X___X__,_____X__,X_______,
  _X___X__,____X___,X_______,
  ______XX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6280[ 54] = { /* code 6280 */
  ________,________,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,___X____,________,
  _XXXXXX_,___X____,________,
  ___X____,___X____,________,
  ___X___X,XXXXXXXX,________,
  ___X____,X______X,________,
  ___X_X__,X_____X_,________,
  ___XX___,_X____X_,________,
  _XXX____,_X___X__,________,
  ___X____,__X_X___,________,
  ___X____,___X____,________,
  ___X____,_XX_X___,________,
  ___X___X,X____XX_,________,
  _X_X_XX_,_______X,X_______,
  __X_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6377[ 54] = { /* code 6377 */
  ________,________,________,
  ___X____,___X____,________,
  ___X____,___X____,________,
  ___X___X,XXXXXXXX,________,
  _XXXXX__,___X____,________,
  ___X___X,XXXXXXXX,________,
  ___X____,___X___X,________,
  ___X__XX,XXXXXXXX,X_______,
  ___X____,___X___X,________,
  ___X____,___X___X,________,
  ___XXXXX,XXXXXXX_,________,
  _XXX___X,___X____,________,
  ___X___X,___XXXXX,X_______,
  ___X___X,___X____,________,
  ___X___X,X__X____,________,
  ___X__X_,_XXX____,________,
  _XXX_X__,___XXX__,________,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6613[ 54] = { /* code 6613 */
  ________,________,________,
  ___XXXXX,XXXXXXX_,________,
  ___X____,______X_,________,
  __X_____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  __X_____,______X_,________,
  __X_____,______X_,________,
  ___XXXXX,XXXXXXX_,________,
  _____X__,________,________,
  ____X___,________,________,
  ___X_XXX,XXXXXXXX,X_______,
  _XX____X,____X___,X_______,
  ______X_,___X____,X_______,
  ____XX__,__X_____,X_______,
  __XX____,_X_____X,________,
  _X_____X,X______X,________,
  _____XX_,__XX__XX,________,
  ____X___,____XX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6709[ 54] = { /* code 6709 */
  ________,________,________,
  _______X,X_______,________,
  _______X,________,________,
  __XXXXX_,XXXXXXXX,________,
  _____XX_,________,________,
  ____XX__,________,________,
  ___XXXXX,XXXXXXX_,________,
  __X_X___,______X_,________,
  XX__X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____XXXX,XXXXXXX_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____X___,___XX_X_,________,
  ________,_____X__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6C14[ 54] = { /* code 6C14 */
  ________,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,________,
  ___X____,________,________,
  __X_____,________,________,
  _X__XXXX,XXXXXXX_,________,
  ________,________,________,
  ________,________,________,
  __XXXXXX,XXXXXXX_,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,______X_,________,
  ________,______X_,X_______,
  ________,______X_,X_______,
  ________,______X_,X_______,
  ________,_______X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6C27[ 54] = { /* code 6C27 */
  ________,________,________,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___X____,________,________,
  __X_XXXX,XXXXXXX_,________,
  _XX_____,________,________,
  ________,________,________,
  ___XXXXX,XXXXXXX_,________,
  ____X___,__X___X_,________,
  ____X___,_X____X_,________,
  __XXXXXX,XXXXX_X_,________,
  _______X,______X_,________,
  __XXXXXX,XXXXX_X_,________,
  _______X,______X_,X_______,
  _XXXXXXX,XXXXXXX_,X_______,
  _______X,_______X,X_______,
  _______X,_______X,X_______,
  _______X,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6C28[ 54] = { /* code 6C28 */
  ________,________,________,
  ____X___,________,________,
  ____XXXX,XXXXXXXX,________,
  ___X____,________,________,
  __X_XXXX,XXXXXXX_,________,
  _X______,________,________,
  __XXXXXX,XXXXXX__,________,
  _______X,______X_,________,
  __XXXXXX,XXXXX_X_,________,
  __X_____,____X_X_,________,
  __X__X__,____X_X_,________,
  __XXXXXX,XXXXX_X_,________,
  ____X___,__X___X_,________,
  ____X___,_X____X_,X_______,
  _____XX_,_X____X_,X_______,
  _______X,XX____X_,X_______,
  _XXXXXX_,__XXX__X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6C2E[ 54] = { /* code 6C2E */
  ________,________,________,
  ____X___,________,________,
  ___XXXXX,XXXXXXXX,________,
  ___X____,________,________,
  __X_XXXX,XXXXXXX_,________,
  _X______,________,________,
  __XXXXXX,XXXXXX__,________,
  _______X,______X_,________,
  ____X__X,___X__X_,________,
  ____X__X,__X___X_,________,
  ___X__XX,XX____X_,________,
  _____XX_,_XX___X_,________,
  __XXX__X,___XX_X_,________,
  ____X__X,__X___X_,X_______,
  ____X__X,_X____X_,X_______,
  ______X_,XX____X_,X_______,
  ___XXX__,__XX___X,X_______,
  __X_____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6DF1[ 54] = { /* code 6DF1 */
  ________,________,________,
  ________,________,________,
  __X___XX,XXXXXXXX,X_______,
  ___X_X__,________,X_______,
  ____XX__,X____X__,X_______,
  ________,X_____X_,________,
  _______X,______X_,________,
  _XX___X_,_______X,________,
  __XX____,__X_____,________,
  _____XXX,XXXXXXXX,X_______,
  ________,__XX____,________,
  ___X____,_X_XX___,________,
  ___X____,XXX_X___,________,
  ___X___X,X_X__X__,________,
  __X___XX,__X___X_,________,
  __X_XX__,__X____X,X_______,
  _X______,__X_____,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6E29[ 54] = { /* code 6E29 */
  ________,________,________,
  _______X,XXXXXX__,________,
  __X___X_,______X_,________,
  ___X_X__,______X_,________,
  ____XX__,______X_,________,
  _____XXX,XXXXXXX_,________,
  _XX__X__,______X_,________,
  __XX__X_,______X_,________,
  ___X__XX,XXXXXXX_,________,
  ________,________,________,
  ___X__XX,XXXXXXX_,________,
  ___X_X__,X___X__X,________,
  ___X_X__,X___X__X,________,
  __X__X__,X___X__X,________,
  __X__X__,X___X__X,________,
  __X__X__,X___X__X,________,
  _X__XXXX,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_6EB6[ 54] = { /* code 6EB6 */
  ________,________,________,
  ________,__X_____,________,
  _XX___XX,XXXXXXXX,________,
  __XX_X__,________,X_______,
  ___X_X__,X___X___,X_______,
  _____X_X,_____X__,X_______,
  ______X_,__X___XX,________,
  _XX__X__,_X_XX___,________,
  __XX____,X___XX__,________,
  _______X,_____XX_,________,
  ______X_,_______X,________,
  ___X_X_X,XXXXXXX_,X_______,
  ___XX_X_,_______X,________,
  __X___X_,_______X,________,
  __X___X_,_______X,________,
  __X___X_,_______X,________,
  _X____XX,XXXXXXXX,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_7387[ 54] = { /* code 7387 */
  ________,X_______,________,
  ________,X_______,________,
  __XXXXXX,XXXXXXXX,________,
  ________,X_______,________,
  _XX_____,X_____XX,________,
  ___X___X,__X__X__,________,
  ___XX__X,_X_XX___,________,
  ______XX,XX_X____,________,
  ____XX__,X___X___,________,
  ___X___X,__X__X__,________,
  __X___X_,_XXX__X_,________,
  ______XX,X__X___X,________,
  ________,X_______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,X_______,________,
  ________,X_______,________,
  ________,X_______,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_751F[ 54] = { /* code 751F */
  ________,________,________,
  ________,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___X____,_X______,________,
  ___XXXXX,XXXXXXXX,________,
  __X_____,_X______,________,
  __X_____,_X______,________,
  _X______,_X______,________,
  ________,_X______,________,
  __XXXXXX,XXXXXXXX,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,_X______,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_7535[ 54] = { /* code 7535 */
  ________,________,________,
  ________,X_______,________,
  ________,X_______,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,X_____X_,________,
  __X_____,X_____X_,________,
  __X_____,X_____X_,________,
  __XXXXXX,XXXXXXX_,________,
  __X_____,X_____X_,________,
  __X_____,X_____X_,________,
  __X_____,X_____X_,________,
  __X_____,X_____X_,________,
  __XXXXXX,XXXXXXX_,________,
  ________,X_______,X_______,
  ________,X_______,X_______,
  ________,X_______,X_______,
  ________,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_76D0[ 54] = { /* code 76D0 */
  ________,________,________,
  ________,___X____,________,
  ____X___,___X____,________,
  _XXXXXXX,___X____,________,
  ____X___,___X_X__,________,
  ____X___,___X__X_,________,
  ____X___,___X___X,________,
  ____X_XX,___X____,X_______,
  ___XXX__,___X____,________,
  _XX_____,___X____,________,
  ___XXXXX,XXXXXX__,________,
  __X___X_,___X__XX,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  __X___X_,___X___X,________,
  _XXXXXXX,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_785D[ 54] = { /* code 785D */
  ________,________,________,
  ________,____X___,________,
  _XXXXXX_,X___X__X,________,
  ___X____,_X__X__X,________,
  ___X____,_X__X_X_,________,
  ___X____,____X___,________,
  __X_____,XXXXXXXX,________,
  __XXXX__,X_______,X_______,
  __X__X__,X_______,X_______,
  _XX__X__,XXXXXXXX,X_______,
  _XX__X__,X_______,X_______,
  __X__X__,X_______,X_______,
  __X__X__,XXXXXXXX,X_______,
  __X__X__,X_______,X_______,
  __X__X__,X_______,X_______,
  __X__X__,X_______,X_______,
  ___XXX__,X____X__,X_______,
  ________,______XX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_78B1[ 54] = { /* code 78B1 */
  ________,________,________,
  ________,_____X_X,________,
  _XXXXXX_,XXXXXXXX,________,
  ___X___X,_____X__,X_______,
  ___X___X,_____X__,X_______,
  ___X___X,_XXXXX__,________,
  __X____X,_____X_X,________,
  __XXXX_X,_XXX_X_X,________,
  _XX__X_X,_X__XX_X,________,
  _XX__X_X,_X__XX_X,________,
  X_X__X_X,_X__XX_X,________,
  __X__X_X,_X__X_XX,________,
  __X__X_X,_X__X_X_,________,
  __X__X_X,_X__X_X_,________,
  __X__XX_,_XXX_XX_,X_______,
  __X__XX_,____X_X_,X_______,
  ___XX_X_,___X___X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_795E[ 54] = { /* code 795E */
  ________,________,________,
  ___X____,____X___,________,
  ____X___,____X___,________,
  ________,_XXXXXX_,________,
  _XXXXXX_,X___X__X,________,
  ______X_,X___X__X,________,
  _____X__,X___X__X,________,
  _____X__,X___X__X,________,
  ____X___,XXXXXXXX,________,
  ___XXX__,X___X__X,________,
  __X_X_X_,X___X__X,________,
  _X__X___,X___X__X,________,
  ____X___,X___X__X,________,
  ____X___,_XXXXXXX,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ____X___,____X___,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_79D1[ 54] = { /* code 79D1 */
  ________,________,________,
  _____XX_,________,________,
  __XXX___,__X___X_,________,
  ____X___,___X__X_,________,
  ____X___,____X_X_,________,
  ____X___,____XXX_,________,
  _XXXXXXX,X____XX_,________,
  ____XX__,_X____X_,________,
  ___XXX__,__X___X_,________,
  ___XX_X_,___X__X_,________,
  __X_X__X,____X_X_,________,
  __X_X__X,______X_,________,
  _X__X___,___XXXXX,X_______,
  ____X__X,XXX___X_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____X___,______X_,________,
  ____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_89E3[ 54] = { /* code 89E3 */
  ________,________,________,
  ____X___,_XXXXXXX,________,
  ___X_XXX,___X___X,________,
  __X___X_,___X___X,________,
  _X____X_,___X___X,________,
  X_XXXXXX,__X_XX_X,________,
  _X__X___,XX____X_,________,
  _X__X___,X_X__X__,________,
  __XXXXXX,X_X__X__,________,
  _X__X___,XXXXXXXX,X_______,
  _X__X___,XX___X__,________,
  _X__X___,X____X__,________,
  __XXXXXX,XXXXXXXX,X_______,
  _X__X___,X____X__,________,
  _X__X___,X____X__,________,
  _X__X___,X____X__,________,
  _X___XXX,X____X__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_8FD8[ 54] = { /* code 8FD8 */
  ________,________,________,
  __X_____,________,________,
  __X___XX,XXXXXXXX,X_______,
  ___X____,____X___,________,
  ___X____,___X____,________,
  ________,___X____,________,
  _XXX____,__X_X___,________,
  ___X____,__X__X__,________,
  ___X____,_XX___X_,________,
  ___X____,X_X___X_,________,
  ___X___X,__X____X,________,
  ___X__XX,__X____X,________,
  ___X_XX_,__X_____,X_______,
  ___XX___,__X_____,________,
  ___XXX__,__X_____,________,
  __X__XX_,__X_____,________,
  _X_____X,XXXXXXXX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_9178[ 54] = { /* code 9178 */
  ________,________,________,
  _XXXXXXX,___X____,________,
  ___X_X__,__X___X_,________,
  ___X_X__,__X____X,________,
  ___X_X__,_X_____X,X_______,
  _XXXXXXX,_XXXXXX_,X_______,
  _X_X_X_X,__X__XX_,________,
  _X_X_X_X,_X_____X,________,
  _X_X_X_X,X_______,X_______,
  _X_X_X_X,__XXXXX_,________,
  _X_X_XXX,__X____X,________,
  _XX____X,_XX___X_,________,
  _X_____X,X__X__X_,________,
  _XXXXXXX,___X_X__,________,
  _X_____X,____XX__,________,
  _X_____X,___X_X__,________,
  _XXXXXXX,XXX___XX,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_94F5[ 54] = { /* code 94F5 */
  ________,________,________,
  __X_____,___X____,________,
  __X_____,XXXXXXXX,________,
  __XXX__X,________,X_______,
  _X_____X,___X____,X_______,
  _X_____X,___X____,X_______,
  _______X,__X_____,________,
  __XXX__X,XXXXXXXX,X_______,
  ___X____,_X____X_,________,
  ___X____,_X____X_,________,
  XXXXXXX_,X_____X_,________,
  ___X____,X____X__,________,
  ___X____,_XX__X__,________,
  ___X____,___XX___,________,
  ___X_XX_,___X_X__,________,
  ___XXX__,_XX___X_,________,
  _______X,X______X,X_______,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_963B[ 54] = { /* code 963B */
  ________,________,________,
  __XXXXX_,________,________,
  _X____X_,XXXXXXXX,________,
  _X____X_,X______X,________,
  _X___X__,X______X,________,
  _X___X__,X______X,________,
  _X___X__,XXXXXXXX,________,
  _X__X___,X______X,________,
  _X___X__,X______X,________,
  _X____X_,X______X,________,
  _X____X_,X______X,________,
  _X____X_,XXXXXXXX,________,
  _X____X_,X______X,________,
  _XXXXX__,X______X,________,
  _X______,X______X,________,
  _X______,X______X,________,
  _X____XX,XXXXXXXX,X_______,
  _X______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontyouyuan18_9650[ 54] = { /* code 9650 */
  ________,________,________,
  __XXX___,XXXXXXX_,________,
  _X___X_X,_______X,________,
  _X___X_X,_______X,________,
  _X__X__X,_______X,________,
  _X__X__X,XXXXXXXX,________,
  _X__X__X,_______X,________,
  _X__X__X,_______X,________,
  _X___X_X,_______X,________,
  _X___X_X,XXXXXXX_,________,
  _X___X_X,__X____X,________,
  _X___X_X,__X___XX,________,
  _XXXXX_X,___X_XX_,________,
  _X_____X,____X___,________,
  _X_____X,_____X__,________,
  _X_____X,______X_,________,
  _X_____X,XXXX___X,X_______,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontyouyuan18_CharInfo[37] = {
   {  18,  18,  3, acGUI_Fontyouyuan18_4F4D } /* code 4F4D */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_4F53 } /* code 4F53 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_516C } /* code 516C */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_5316 } /* code 5316 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_538B } /* code 538B */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_539F } /* code 539F */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_53F8 } /* code 53F8 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_5927 } /* code 5927 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_5BFC } /* code 5BFC */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_5EA6 } /* code 5EA6 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6001 } /* code 6001 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_603B } /* code 603B */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6280 } /* code 6280 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6377 } /* code 6377 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6613 } /* code 6613 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6709 } /* code 6709 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6C14 } /* code 6C14 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6C27 } /* code 6C27 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6C28 } /* code 6C28 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6C2E } /* code 6C2E */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6DF1 } /* code 6DF1 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6E29 } /* code 6E29 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_6EB6 } /* code 6EB6 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_7387 } /* code 7387 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_751F } /* code 751F */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_7535 } /* code 7535 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_76D0 } /* code 76D0 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_785D } /* code 785D */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_78B1 } /* code 78B1 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_795E } /* code 795E */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_79D1 } /* code 79D1 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_89E3 } /* code 89E3 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_8FD8 } /* code 8FD8 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_9178 } /* code 9178 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_94F5 } /* code 94F5 */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_963B } /* code 963B */
  ,{  18,  18,  3, acGUI_Fontyouyuan18_9650 } /* code 9650 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop36 = {
   0x9650 /* first character */
  ,0x9650 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 36] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop35 = {
   0x963B /* first character */
  ,0x963B /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 35] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop36 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop34 = {
   0x94F5 /* first character */
  ,0x94F5 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 34] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop35 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop33 = {
   0x9178 /* first character */
  ,0x9178 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 33] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop34 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop32 = {
   0x8FD8 /* first character */
  ,0x8FD8 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 32] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop33 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop31 = {
   0x89E3 /* first character */
  ,0x89E3 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 31] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop32 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop30 = {
   0x79D1 /* first character */
  ,0x79D1 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 30] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop31 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop29 = {
   0x795E /* first character */
  ,0x795E /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 29] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop30 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop28 = {
   0x78B1 /* first character */
  ,0x78B1 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 28] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop29 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop27 = {
   0x785D /* first character */
  ,0x785D /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 27] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop28 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop26 = {
   0x76D0 /* first character */
  ,0x76D0 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 26] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop27 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop25 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 25] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop26 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop24 = {
   0x751F /* first character */
  ,0x751F /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 24] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop25 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop23 = {
   0x7387 /* first character */
  ,0x7387 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 23] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop24 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop22 = {
   0x6EB6 /* first character */
  ,0x6EB6 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 22] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop23 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop21 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop22 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop20 = {
   0x6DF1 /* first character */
  ,0x6DF1 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop21 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop19 = {
   0x6C2E /* first character */
  ,0x6C2E /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop20 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop18 = {
   0x6C27 /* first character */
  ,0x6C28 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop19 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop17 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop18 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop16 = {
   0x6709 /* first character */
  ,0x6709 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop17 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop15 = {
   0x6613 /* first character */
  ,0x6613 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop16 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop14 = {
   0x6377 /* first character */
  ,0x6377 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop15 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop13 = {
   0x6280 /* first character */
  ,0x6280 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop14 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop12 = {
   0x603B /* first character */
  ,0x603B /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop13 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop11 = {
   0x6001 /* first character */
  ,0x6001 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[ 10] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop12 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop10 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  9] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop11 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop9 = {
   0x5BFC /* first character */
  ,0x5BFC /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  8] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop10 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop8 = {
   0x5927 /* first character */
  ,0x5927 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  7] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop9 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop7 = {
   0x53F8 /* first character */
  ,0x53F8 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  6] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop6 = {
   0x539F /* first character */
  ,0x539F /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  5] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop5 = {
   0x538B /* first character */
  ,0x538B /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  4] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop4 = {
   0x5316 /* first character */
  ,0x5316 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  3] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop3 = {
   0x516C /* first character */
  ,0x516C /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  2] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop2 = {
   0x4F53 /* first character */
  ,0x4F53 /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  1] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontyouyuan18_Prop1 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_Fontyouyuan18_CharInfo[  0] /* address of first character */
  ,&GUI_Fontyouyuan18_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontyouyuan18 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,18 /* height of font  */
  ,18 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontyouyuan18_Prop1}
  ,15 /* Baseline */
  ,8 /* Height of lowercase characters */
  ,12 /* Height of capital characters */
};

