/*********************************************************************
*          Portions COPYRIGHT 2014 STMicroelectronics                *
*          Portions SEGGER Microcontroller GmbH & Co. KG             *
*        Solutions for real time microcontroller applications        *
**********************************************************************
*                                                                    *
*        (c) 1996 - 2013  SEGGER Microcontroller GmbH & Co. KG       *
*                                                                    *
*        Internet: www.segger.com    Support:  support@segger.com    *
*                                                                    *
**********************************************************************

** emWin V5.22 - Graphical user interface for embedded applications **
All  Intellectual Property rights  in the Software belongs to  SEGGER.
emWin is protected by  international copyright laws.  Knowledge of the
source code may not be used to write a similar product.  This file may
only be used in accordance with the following terms:

The  software has  been licensed  to STMicroelectronics International
N.V. a Dutch company with a Swiss branch and its headquarters in Plan-
les-Ouates, Geneva, 39 Chemin du Champ des Filles, Switzerland for the
purposes of creating libraries for ARM Cortex-M-based 32-bit microcon_
troller products commercialized by Licensee only, sublicensed and dis_
tributed under the terms and conditions of the End User License Agree_
ment supplied by STMicroelectronics International N.V.
Full source code is available at: www.segger.com

We appreciate your understanding and fairness.
----------------------------------------------------------------------
File        : GUIDEMO_Start.c
Purpose     : GUIDEMO initialization
----------------------------------------------------------------------
*/

/**
  ******************************************************************************
  * @file    GUIDEMO_Start.c
  * @author  MCD Application Team
  * @version V1.1.2
  * @date    28-January-2014
  * @brief   GUIDEMO initialization
  ******************************************************************************
  * @attention
  *
  * Licensed under MCD-ST Liberty SW License Agreement V2, (the "License");
  * You may not use this file except in compliance with the License.
  * You may obtain a copy of the License at:
  *
  *        http://www.st.com/software_license_agreement_liberty_v2
  *
  * Unless required by applicable law or agreed to in writing, software 
  * distributed under the License is distributed on an "AS IS" BASIS, 
  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  * See the License for the specific language governing permissions and
  * limitations under the License.
  *
  ******************************************************************************
  */


//#include "GUIDEMO.h"
#include "GUI.h"
#include "stdio.h"


/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/
// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong16;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0   (GUI_ID_USER + 0x00)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_1   (GUI_ID_USER + 0x02)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 20, 20, 80, 20, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 20, 40, 80, 20, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Window'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, (0x00C08000));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetText(hItem, "hello");
    TEXT_SetTextColor(hItem, (0x00FFFFFF));
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetText(hItem, "wolrd");
    TEXT_SetTextColor(hItem, (0x00FFFFFF));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}


/*************************** End of file ****************************/


//void MainTask(void);

//void MainTask(void) {
//    GUI_MEMDEV_Handle hMemJPEG;
//    GUI_JPEG_INFO JpegInfo;
//    GUI_Init();
//    CreateWindow();
////    CreateFramewin();
////    GUI_JPEG_GetInfo(_acImage_0,sizeof(_acImage_0), &JpegInfo);
////    hMemJPEG = GUI_MEMDEV_CreateEx(0,0,JpegInfo.XSize,JpegInfo.YSize,GUI_MEMDEV_HASTRANS);
////    GUI_MEMDEV_Select(hMemJPEG);
////    GUI_JPEG_Draw(_acImage_0,sizeof(_acImage_0),0,0);
////    GUI_MEMDEV_Select(0);
////    GUI_MEMDEV_WriteAt(hMemJPEG,0,0);
//  
//    while(1)
//    {
//        GUI_Delay(10);
//    }
//}

//void MainTask(void) {
////  char dbuf[32];
////  int i=0;
////  GUI_Init();
////  GUI_SetBkColor(GUI_BLUE);
////  GUI_Clear();
////  GUI_SetFont(&GUI_Font8x16);
////  GUI_SetTextMode(GUI_TM_TRANS);
////  GUI_DispString("www.test.com \navailable");
//////  sprintf(dbuf,"hello %dth\n",i);
//////  GUI_DispStringHCenterAt(dbuf,400,400);
////  while(1)
////  {       
////      sprintf(dbuf,"This is %dth\n",i);
//////      GUI_DispString(dbuf);
////      GUI_DispStringHCenterAt(dbuf,400,10);
////      GUI_Delay(1000);
////      i++;
////  }
//  WM_SetCreateFlags(WM_CF_MEMDEV);
//  GUI_Init();
//  CreateFramewin();
//  while(1)
//  {       
//      GUI_Delay(10);
//  }  
//}


//void MainTask(void) {
//  char dbuf[32];
//  int i=0;
//  GUI_Init();
//  GUI_SetBkColor(GUI_BLUE);
//  GUI_Clear();
//  GUI_SetFont(&GUI_Font8x16);
//  GUI_SetTextMode(GUI_TM_TRANS);
//  GUI_DispString("www.test.com \navailable");
////  sprintf(dbuf,"hello %dth\n",i);
////  GUI_DispStringHCenterAt(dbuf,400,400);
//  while(1)
//  {       
//      sprintf(dbuf,"This is %dth\n",i);
////      GUI_DispString(dbuf);
//      GUI_DispStringHCenterAt(dbuf,400,10);
//      GUI_Delay(1000);
//      i++;
//  }
////  WM_SetCreateFlags(WM_CF_MEMDEV);
////  GUI_Init();
////  GUIDEMO_Main();
//}

/*************************** End of file ****************************/

